### ISSUE TITLE
未正常打印

### ISSUE THREAD

**Issue by Kiss-World** [l1xnan/obsidian-better-export-pdf#1]
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/44720566/c9d4b1f4-5dd0-448a-aeeb-edd53655c7a0)

**Comment by l1xnan** [comment]
导出 PDF 前需要在`外观`中将颜色切换为`浅色`，深色模式会显示异常，下一个版本针对这一点做一下优化
