### ISSUE TITLE
BUG：表格跨页导出问题

### ISSUE THREAD

**Issue by YIRU69** [l1xnan/obsidian-better-export-pdf#101]
你好，我在使用插件进行表格的导出的时候发现的表格在跨页的时候，打印不正常，具体表现如下：

插件导出的效果
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/48148292/b4bdadd4-e2da-4046-8432-6f6f424ba3e2)

使用导出 css 的效果
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/48148292/0e92d912-d0d8-4ee9-aac0-48900b7dc7f5)

另外还有一个问题，当鼠标停留在表格中，打印会把悬浮的颜色打印出来，具体表现如下：
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/48148292/902c4c3b-528f-4a49-bae1-7c6cbcc11ad1)

**Comment by YIRU69** [comment]
鼠标悬浮的颜色是指，我用css做了一个当我的鼠标指针悬浮在表格上，会高亮这种

**Comment by l1xnan** [comment]
插件是最新版本的么？复现这个问题的文档能否共享出来？

**Comment by YIRU69** [comment]
[1.zip](https://github.com/l1xnan/obsidian-better-export-pdf/files/14049201/1.zip)
 rar 后缀
 
 你看你一下，我用了打印css

**Comment by l1xnan** [comment]
是否有自定义页边距?

**Comment by YIRU69** [comment]
我测试库里面用的应该是默认边距呀。你是通过我提供的测试库测试的吗？

**Comment by l1xnan** [comment]
那你调整下边距试试😂，表格问题出现好多次，底层的控制不了，可以调整的配置不多，还不行就没办法了🤷‍♂️

**Comment by YIRU69** [comment]
> 那你调整下边距试试😂，表格问题出现好多次，底层的控制不了，可以调整的配置不多，还不行就没办法了🤷‍♂️

好的，辛苦了。为什么默认导出和插件导出有这个不同呢？不太懂。

**Comment by YIRU69** [comment]
我自己仔细对比了一下区别
1. 我调整边距没有明显作用，唯一可以的是避免表格跨页。
2. 出现问题是由于，表格跨页，默认导出的表格是表头会重新打印一次，形成新的表头，而插件导出的形成了新的表头，但是形成新的表头并没有给出相应的位置，所以看起来就是重合的。

这样看起来，是否不是底层的原因呢？个人的想法

**Comment by l1xnan** [comment]
插件原理逆向了官方的打印流程，把重新生成的 dom 和 css 复制到 webview 中，调用的是 webview 的 printToPDF api, 虽然尽量保持原样复制，但是官方的会存在细微差异，webview 中的打印 API 和 BrowserView 的打印API结果也可能会有差别

**Comment by l1xnan** [comment]
> 我自己仔细对比了一下区别
> 
> 1. 我调整边距没有明显作用，唯一可以的是避免表格跨页。
> 2. 出现问题是由于，表格跨页，默认导出的表格是表头会重新打印一次，形成新的表头，而插件导出的形成了新的表头，但是形成新的表头并没有给出相应的位置，所以看起来就是重合的。
> 
> 这样看起来，是否不是底层的原因呢？个人的想法

我检查了表格元素的 CSS，没有发现什么异常的地方

**Comment by l1xnan** [comment]
碰到几次这种问题，一般是某一行表格没有完全打印出边框的时候
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/10247efc-4476-4179-872c-c1658482b48b)

**Comment by YIRU69** [comment]
我进一步进行了测试，发现使用 Blue Topaz 主题，然后进行导出，就不会出现这个问题，如果使用默认主题就会出现这个问题，看来css 的控制对这个有一定影响呀

**Comment by l1xnan** [comment]
> 我进一步进行了测试，发现使用 Blue Topaz 主题，然后进行导出，就不会出现这个问题，如果使用默认主题就会出现这个问题，看来css 的控制对这个有一定影响呀

主题是影响了各种边距和间距，对表格的打印相关的CSS属性应该没有特殊的定制

**Comment by YIRU69** [comment]
继续进行了测试，发现 跟 Blue Topaz 主题无关，我调节了缩放比例，有的缩放比例会出现重叠，有的缩放比例可以有效的导出

**Comment by YIRU69** [comment]
看起来确实很棘手，没办法解决

**Comment by l1xnan** [comment]
> 看起来确实很棘手，没办法解决

是的，应该和 CSS 样式关系不大，网页转PDF质量一直不太高，各种小毛病，只能是凑合着用，想提高质量还是要看 latex 和 typst。
