### ISSUE TITLE
预览时，能否将pdf分页，或者在预览页面显示页脚

### ISSUE THREAD

**Issue by LingJingMaster** [l1xnan/obsidian-better-export-pdf#102]

**Comment by l1xnan** [comment]
Chrome 的分页打印预览是自己实现的，在 Electron 中没有相关组件。目前预览只是为了看这个页面元素是否正常显示，有没有缺失，以及颜色/字体等是否正常，当前做不到准确的分页，要处理的细节太多，已经脱离了这个项目的范畴。前面尝试过 `pagedjs` 方案，但是和 Obisidian 有冲突，后面有空可以花时间再探索下。只能遗憾地说，短期内这个功能无法实现

**Comment by LingJingMaster** [comment]
好的，虽然有点遗憾，但是十分感谢，这个插件帮到了我很多！！！
