### ISSUE TITLE
[Bug] 正好在表格中间分页的时候，会导致文本覆盖

### ISSUE THREAD

**Issue by Kun-Wang-RSP** [l1xnan/obsidian-better-export-pdf#112]
带page header
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/119379600/35c8ef0e-bf63-4c78-91f3-f1598cecc920)

不带page header
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/119379600/c86b21eb-599b-4459-83bf-eeeb6348082d)

**Comment by l1xnan** [comment]
这是 chromium 存在的BUG，网上可以搜索到一些相关资料，例如: 
- [Table header overlaps with content in Chrome print preview](https://stackoverflow.com/questions/76801130/table-header-overlaps-with-content-in-chrome-print-preview)
- https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1524

前面的朋友也有相关 issue https://github.com/l1xnan/obsidian-better-export-pdf/issues/101 ，可以通过调整页边距或者CSS来尝试临时规避，只是这种方案并不通用，目前确实没有好的解决办法。

我这边后面尝试添加一些表格分页检测干预算法，希望能进一步缓解这个问题，只是可能需要等待一段时间。

**Comment by l1xnan** [comment]
跟踪 #107
