### ISSUE TITLE
[BUG] 不能生成pdf文件

### ISSUE THREAD

**Issue by wwjCMP** [l1xnan/obsidian-better-export-pdf#120]
![Snipaste_2024-02-19_06-34-03](https://github.com/l1xnan/obsidian-better-export-pdf/assets/32979859/22c07e27-dd72-439f-b2b6-716eac7ea1c3)
一直停在这个页面

**Comment by l1xnan** [comment]
你能否提供下如下信息:
1. 是所有文档都有问题，还是仅仅当前这个文档?
2. `ctrl+shift+i` 打开终端看是否要报错?
3. 在插件设置中打开 `Debug mode`, 在预览界面点击`Debug`, 打开Console看是否有报错
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/f686b310-7e22-4d28-8062-9e13824ebf67)

**Comment by ttbug** [comment]
遇到个类似的问题，原因是文档中嵌入了excalidraw，导出提示dom not ready，官方的可以正常导出

**Comment by wwjCMP** [comment]
![Snipaste_2024-02-26_02-54-32](https://github.com/l1xnan/obsidian-better-export-pdf/assets/32979859/576f8770-2885-4237-8a99-ef4ce438d29e)

**Comment by l1xnan** [comment]
@wwjCMP 根据报错，修改了点地方，打了个包，试一下是否OK?

[better-export-pdf.zip](https://github.com/l1xnan/obsidian-better-export-pdf/files/14399791/better-export-pdf.zip)
