### ISSUE TITLE
Seems incompatible with surfing plugin

### ISSUE THREAD

**Issue by Ninecr** [l1xnan/obsidian-better-export-pdf#121]
When a tab using the surfing plugin is opened, no matter what document is exported, it will be displayed normally in the preview interface, but the final exported content will be the tab opened by the surfing plugin.

**Comment by l1xnan** [comment]
Sorry, I don't quite understand what happened, could you please provide some screenshots/videos?

**Comment by Ninecr** [comment]
Sorry, the following screenshot reproduces and illustrates the issue：
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/59114053/82856209-98c2-4f53-809a-e731f4b1687c)

**Comment by l1xnan** [comment]
I have found the cause of the problem and the next version fixes it.
