### ISSUE TITLE
Get header/footer data from each document's YAML

### ISSUE THREAD

**Issue by NaeemBolchhi** [l1xnan/obsidian-better-export-pdf#124]
I am currently using this plugin to prepare lecture notes. It can be quite troubling to repeatedly change things within the plugin settings before exporting each document. If you could optionally move the header/footer customization to YAML, then each document could have a defined header and footer in the `.md` file, thereby reducing the need to configure the plugin every single time I'm printing to a pdf.

And thank you for this wonderful plugin.

**Comment by merlinuwe** [comment]
I have a similar wish. My informations are in yaml.

```
...text
filename: CT23A LABV INF KA01 US 2023-11-08 Tabelle, pdf, Obsidian
erstellt: Freitag, 22. September 2023, 08:37:11 Uhr
geändert: Montag, 25. Dezember 2023, 10:31:13 Uhr
Termin: 2023-11-08T11:55:00
...
```

If I could use them, I would not ask you to change the date format accordingly. ;-)

**Comment by l1xnan** [comment]
@NaeemBolchhi I'll try to add `pdf-header`, `pdf-footer` fields to front matter in the next version.

**Comment by l1xnan** [comment]
@merlinuwe The display of the corresponding content in the current header and footer via `class="xxx"` (title, date .etc) is handled by the underlying chromium, and there is no way for the plugin to intervene and read the information in the frontmatter. This can be solved later by using placeholders, for example:
```html
-- header/footer
<div>
  <span>${filename}-${erstellt}</span>
</div>
```
