### ISSUE TITLE
Margins Not Exporting

### ISSUE THREAD

**Issue by CaffeineEvergreen** [l1xnan/obsidian-better-export-pdf#127]
Heya! Firstly, thanks for all your hard work, this plugin is a lifesaver.

I have noticed that the margins are suddenly not exporting anymore? I can set them to whatever I want, but the exported document always has default 1" margins. I have tried all settings (None, Small, etc), changing to 0, restarting Obsidian, reinstalling, updating, etc. All margins are coming out the same.

I have attached screenshots of the in-app settings all set to 0/None, and the resulting PDF to show what I mean.

Thanks!
![Screenshot 2024-02-20 162044](https://github.com/l1xnan/obsidian-better-export-pdf/assets/160670912/3c5371bd-7cdf-4134-ad10-993e2c48b7d4)
[This Is a Test Note.pdf](https://github.com/l1xnan/obsidian-better-export-pdf/files/14351257/This.Is.a.Test.Note.pdf)

**Comment by l1xnan** [comment]
Sorry, it does have issues, it was fixed in version 1.5.5.

**Comment by CaffeineEvergreen** [comment]
> Sorry, it does have issues, it was fixed in version 1.5.5.

No worries at all, I appreciate you looking into it so fast! I tried the update, but it's still being weird (although improved!)
Honestly, all good, just thought I'd mention it. It's still taking a huge amount of tedium off my hands, so much appreciated, lol

**Comment by l1xnan** [comment]
On your screenshot, `margin: none`, but showing the custom margin form, there's a problem with the linkage, although I haven't reproduced it. Other than that, are there any weird questions?
