### ISSUE TITLE
[FR] Export Multiple Notes to PDF

### ISSUE THREAD

**Issue by l1xnan** [l1xnan/obsidian-better-export-pdf#129]
1. Export the notes specified by `Table of Contents.md` to a PDF, preserving the order, and output the contents page
    ```markdown
	---
    toc: true
    ---

    [[Page 1| Title1]]
    [[Page 2]]
    [[Page 3]]
    ```

2. Export notes from the folder as one or more PDF files.

**Comment by like1river2east** [comment]
Hi there! At present, the 'TOC method' that exports along with the link PDF is equivalent to only exporting one layer of internal links. 
I have used another note taking software that supports a 'crawler search', which means traversing all the linked files under a note file, as well as the linked files within the linked files, And it provides options for users to choose the traversal depth (such as 1 layer, 2 layers, 3 layers, or traversal all). 
ps. also see https://forum.obsidian.md/t/export-md-file-with-all-linked-files-images-recursively-convert-to-html/27597


I was wondering if the better export pdf plugin can traverse deeper files and merge them together into one PDF (with support for clicking to jump)? Thanks!

**Comment by l1xnan** [comment]
@like1river2east It is supported.

**Comment by like1river2east** [comment]
> @like1river2east It is supported.

Is that true? I mean not only the notes linked in "Table of Contents.md", but also the further linked notes within the notes, traversing all the linked notes to the end, and exporting all of them to PDF and merging them into a single PDF. I tried your plugin today, and it seems that only one level of notes below can be exported. 🙏

**Comment by l1xnan** [comment]
@like1river2east Oh, it only exports the notes linked in "Table of Contents.md", it will not export the notes linked within the notes. This is more in line with expectations. If you export a folder, it will export all the notes under that folder.

**Comment by like1river2east** [comment]
> @like1river2east Oh, it only exports the notes linked in "Table of Contents.md", it will not export the notes linked within the notes. This is more in line with expectations. If you export a folder, it will export all the notes under that folder.

Thanks for your reply! I know the feature of "export the folder". However, what I actually need is to share one "TOC.md" and all its outlink notes (not only one sublayer linked notes) to my friends, with the support for clicking to jump through the "TOC.md". And I was wondering if you can add this feature? Thanks in advance.

**Comment by like1river2east** [comment]
> > @like1river2east Oh, it only exports the notes linked in "Table of Contents.md", it will not export the notes linked within the notes. This is more in line with expectations. If you export a folder, it will export all the notes under that folder.
> 
> Thanks for your reply! I know the feature of "export the folder". However, what I actually need is to share one "TOC.md" and all its outlink notes (not only one sublayer linked notes) to my friends, with the support for clicking to jump through the "TOC.md". And I was wondering if you can add this feature? Thanks in advance.

By the way, it is hard for my to move all the outlink notes of the "TOC.md" to one folder, as they are already placed randomly in a large folder. Thus I think your plugin is really potential to satisfy my requirement.
