### ISSUE TITLE
在snippets添加的css片段，无法在导出时正确渲染

### ISSUE THREAD

**Issue by edwardostara** [l1xnan/obsidian-better-export-pdf#134]
在snippets添加的css片段，无法在导出时正确渲染，而官方pdf导出渲染正常。
css片段是实现双栏效果

我用本插件时的导出效果，如下:
![self](https://github.com/l1xnan/obsidian-better-export-pdf/assets/44975278/60acbc20-a055-4146-b518-99ff4f6840f7)
用官方pdf导出的效果，如下：
![official](https://github.com/l1xnan/obsidian-better-export-pdf/assets/44975278/6e265ca7-1349-4ca4-8ef8-29f201605dd6)

css片段文件，不能上传css文件，改成了txt文件
[column.txt](https://github.com/l1xnan/obsidian-better-export-pdf/files/14449853/column.txt)

测试文档
[测试.md](https://github.com/l1xnan/obsidian-better-export-pdf/files/14449867/default.md)

**Comment by l1xnan** [comment]
问题应该因为不支持 `cssclasses` 造成的
