### ISSUE TITLE
Feature Request: Single Command Instant Export

### ISSUE THREAD

**Issue by uthmanmoh** [l1xnan/obsidian-better-export-pdf#137]
Not sure if this is possible in Obsidian, but one thing I would really benefit from is a separate single command like `Better PDF Instant Export` or something that I can run that will skip the settings and preview page and export right away. So this would mean as soon as I run the command it opens the OS file picker rather than confirming the settings first. I think this would be useful for people that always export using the same configurations and just want 1 less click to move faster. It could just use the saved configs from a previous attempt and export using those.

An alternative that could also be beneficial in solving the same problem is enabling the `Enter` key to select export from the preview and configuration popup. Currently I'm forced to use the mouse which gets annoying when you are exporting multiple times. I want a workflow where I can just stay on my keyboard and do something like `Cmd-p` -> `Better PDF Export` -> `Enter` -> `Enter` (for default file name and location).

Thank you so much for the plugin btw! Really liking using it so far over the default pdf exporting in Obsidian

**Comment by l1xnan** [comment]
Thank you for your suggestion. I first tried to add the `Enter` shortcut key. However, there's one thing to note: one purpose of the preview is to wait for markdown rendering to complete. You can't press Enter immediately after the preview appears; you may need to wait a few seconds. Implementing the instant export feature would require modifying more code, so it will take a bit longer to complete.

**Comment by uthmanmoh** [comment]
Great! I just tested the `Enter` to export, and it works perfectly. I'm satisfied now with the feature request, so feel free to close it if you wish.

**Comment by merlinuwe** [comment]
Thank you very much for this ergonomic feature.

If I try to produce a pdf file with your great plugin, I run into this issue:

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4138869/9a7c375e-018c-4c69-8963-a1046946d5c3)

It would be perfect, if the output file gets an (optional) trailing or leading timestamp to prevent this.

**Comment by l1xnan** [comment]
> Thank you very much for this ergonomic feature.
> 
> If I try to produce a pdf file with your great plugin, I run into this issue:
> 
> ![image](https://private-user-images.githubusercontent.com/4138869/316332252-9a7c375e-018c-4c69-8963-a1046946d5c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMjkyMDMsIm5iZiI6MTcxMTMyODkwMywicGF0aCI6Ii80MTM4ODY5LzMxNjMzMjI1Mi05YTdjMzc1ZS0wMThjLTRjNjktODk2My1hMTA0Njk0NmQ1YzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjVUMDEwODIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjJiNmVkNzkzZDYyNjQyZmY4MDM2MDM1YWQ5OGUwNzI3ZTQ4ZWFiOTYyY2E3OWIyNmIxZjQ2MmMwNzFhZTM2MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.DK7gnM7lpSik14TtR6kQImyhvsY3vs83SLUNwQuJbxk)
> 
> It would be perfect, if the output file gets an (optional) trailing or leading timestamp to prevent this.

Thank you for your suggestion. I will try to add an optional configuration in the next version to address it.
