### ISSUE TITLE
'Failed to Load Plugin'

### ISSUE THREAD

**Issue by jhwright** [l1xnan/obsidian-better-export-pdf#14]
i installed the latest plugin 1.0.4 according to instructions here, and receive 'Failed to Load Plugin' error when attempting to activate.    I deactivated all plugins with no beneficial result.  Any suggestions?

**Comment by BossCodersHQ** [comment]
I got the same error, Looks like 1.0.3 works for me though.
Only issue is it doesn't seem to have the `Export the outline bookmarks` feature that I needed :'(

**Comment by l1xnan** [comment]
The plug-in needs to be downloaded the zip file from the [release](https://github.com/l1xnan/obsidian-better-export-pdf/releases/download/1.0.5/obsidian-better-export-pdf-1.0.5.zip) page

See figure for usage:
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/bf80cec6-aa41-4189-9da8-8f87106b0c0f)
