### ISSUE TITLE
Do not read files in nested directories

### ISSUE THREAD

**Issue by Agoines** [l1xnan/obsidian-better-export-pdf#158]
I have multiple subdirectories under the root directory and multiple.md files under the subdirectories. But exporting PDFs doesn't work. (from Google Translate)

<img width="995" alt="截屏2024-03-31 16 26 55" src="https://github.com/l1xnan/obsidian-better-export-pdf/assets/50230626/92b83839-5b2b-4134-8dd0-06eb014d8938">

**Comment by gaelthas** [comment]
我手点多个文件夹，然后用[https://github.com/wmjordan/PDFPatcher](url)连起来了。不知道作者有没有计划增加这个功能，过段时间有空了我试试能不能改改

**Comment by l1xnan** [comment]
目前只读取了文件夹下笔记文件，没有解析子文件夹，嵌套文件夹下个版本支持。可以先用定义一个目录文件规避下，具体参考下文档: [多文档>自定义导出](https://github.com/l1xnan/obsidian-better-export-pdf/blob/master/README.zh.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AF%BC%E5%87%BA)

文件夹导出不能保证笔记导出的顺序，调查下，大家一般在什么场景下会这样导出?

**Comment by Agoines** [comment]
> 文件夹导出不能保证笔记导出的顺序，调查下，大家一般在什么场景下会这样导出?

我是用文件夹分章节的，也就是类似

根目录/日常/xxx
根目录/日常/xxx2
根目录/日常/xxx3
根目录/其他/xxx

或者下面这种

日常/2021/xxx
日常/2023/xxx

做一个同一个类型其中内容进一步区分

**Comment by Agoines** [comment]
> 文件夹导出不能保证笔记导出的顺序
没有开发过 ob 插件，不是很了解 ob 插件。ob 插件能不能获取时间/名称，或者写一个控件让用户自行排序？

**Comment by gaelthas** [comment]
> 目前只读取了文件夹下笔记文件，没有解析子文件夹，嵌套文件夹下个版本支持。可以先用定义一个目录文件规避下，具体参考下文档: [多文档>自定义导出](https://github.com/l1xnan/obsidian-better-export-pdf/blob/master/README.zh.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AF%BC%E5%87%BA)
> 
> 文件夹导出不能保证笔记导出的顺序，调查下，大家一般在什么场景下会这样导出?

多个章(一级文件夹)，每章多个小结(二级文件夹)，每小结一个md文件

**Comment by l1xnan** [comment]
@gaelthas @Agoines 先支持了读取子目录，已发版。
手动排序看看  [多文档>自定义导出](https://github.com/l1xnan/obsidian-better-export-pdf/blob/master/README.zh.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%AF%BC%E5%87%BA) 功能后面优化下，可以基于目录自动生成这个文件，然后手动在处理

**Comment by gaelthas** [comment]
感谢，辛苦了
