### ISSUE TITLE
Foldable Callouts not supported

### ISSUE THREAD

**Issue by zauberparacelsus** [l1xnan/obsidian-better-export-pdf#165]
Foldable callouts do not appear to be supported by Better PDF, in that they display as always-unfolded.

Given that PDFs are page-based though, I am not entirely sure it would be viable?  Not unless it was instead treated as a spoiler (ie: click to hide/unhide instead of fold/unfold).

**Comment by l1xnan** [comment]
PDF does not support interaction, it needs to display all the folded content
