### ISSUE TITLE
An embedded note from calendar plugin is sometimes not in the preview and therefore not in the generated pdf-file

### ISSUE THREAD

**Issue by merlinuwe** [l1xnan/obsidian-better-export-pdf#170]
If I print the file FW21A CTR (20240410-185659) with your plugin, I don't always (~ 50 %, but not an exact even-odd-issue) get the embedded calendar information ![[Kalender - FW]] in the pdf file.

[FW21A CTR (20240410-185659).md](https://github.com/l1xnan/obsidian-better-export-pdf/files/14935628/FW21A.CTR.20240410-185659.md)

[Menü.md](https://github.com/l1xnan/obsidian-better-export-pdf/files/14935633/Menu.md)

[Kalender - FW.md](https://github.com/l1xnan/obsidian-better-export-pdf/files/14935641/Kalender.-.FW.md)

[abcdef.md](https://github.com/l1xnan/obsidian-better-export-pdf/files/14935658/abcdef.md)

The plugin for generating the calendar is this:

https://github.com/YukiGasai/obsidian-google-calendar

Resulting export-files:

_without_ the calendar information:

[FW21A CTR (20240410-185659).pdf](https://github.com/l1xnan/obsidian-better-export-pdf/files/14935701/FW21A.CTR.20240410-185659.pdf)

_with_ the calendar information:

[FW21A CTR (20240410-185659)with-calendar-information.pdf](https://github.com/l1xnan/obsidian-better-export-pdf/files/14935714/FW21A.CTR.20240410-185659.with-calendar-information.pdf)

---

When there is _no_ calendar information, your preview looks like this:

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4138869/657f3a32-688e-4f55-9c31-76bfec4f5056)

When I press your refresh-Button, your preview looks like this and a the complete pdf-file can get exported:

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4138869/9539f9db-9e8d-443d-960a-0a1261e1e8d3)

---

The problem is, that I don't always see, _which_ information is lost, because my notes are long (~ 10 pages of DIN A4) and I use some embedded notes. A good workaround would be, it the refresh-button gets pressed automatically. ;-)

**Comment by l1xnan** [comment]
Currently, it's not possible to accurately determine the end time of the calendar plugin rendering. The preview page is displaying results that haven't finished rendering yet. To mitigate this issue, I've added a DOM change listener.

**Comment by merlinuwe** [comment]
When there is a google calendar in the note, I get no preview with the latest release. (I waited for ~2 minutes.):

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4138869/2c1e59bc-ba5b-4433-9db2-cf7c2d5e691f)

Error message: "dom not ready"

(But Obsidians native pdf export runs.)

**Comment by l1xnan** [comment]
I did not encounter this issue after installing the supercharged links plugin. It seems there is a plugin conflict. Did the old version have this problem?

**Comment by merlinuwe** [comment]
No, I would have noticed the many log entries.

**Comment by l1xnan** [comment]
I removed a version of the logic and just added 3s waiting to see if any more conflicts occurred:
[better-export-pdf.zip](https://github.com/l1xnan/obsidian-better-export-pdf/files/14970821/better-export-pdf.zip)

**Comment by merlinuwe** [comment]
I tried your package with [FW21A CTR (20240410-185659).md](https://github.com/l1xnan/obsidian-better-export-pdf/files/14935628/FW21A.CTR.20240410-185659.md)

I don't see a preview with this file, even if I wait for ~2 minutes.

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4138869/1ecd76c3-0603-4b01-be7f-7a0098274970)

Console:

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4138869/b9774077-91cf-43a4-a737-a3153d88424b)

**Comment by merlinuwe** [comment]
Good news:

1. With the latest release 1.7.3, I now can comment out paragraphs with 

%% at the beginning and end. %%

2. The issue with the google calendar plugin seems to be solved. Great. Thank you very much.

3. I can see a preview of an other long and complex note.

Finetuning:

I don't know, if you can control this pagebreak inside the calendar output:

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4138869/4a2f8176-a39e-43ce-99e5-9f9cfbd60679)

The native obsidian pdf export has the same issues:

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4138869/2416807c-de4e-4443-b7e8-cb3b0c555e1c)


---

An other issue:

When I try to built a pdf-file from a note with a tasks plugin element at the end, there is no preview in your plugin and the console shows this:

`````
```tasks
path includes {{query.file.filename}}
not done
group by heading
```

`````



![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4138869/15c3f259-629d-4d12-9b12-5e057df61893)


But this issue is not as easy to isolate, because this one works:

`````
---
aliases:
  - Notiz
tags:
  - Notiz
filename: muell-better-export-plugin-tasks-plugin
erstellt: Monday, 15. April 2024, 10:14:04 Uhr
geändert: Monday, 15. April 2024, 10:14:04 Uhr
updated_at: 242024-04-15T10:14:32.498+02:00
---

- [x] Task number 1
- [ ] Task number 2


## 1 ErsteÜberschrift

```tasks
path includes {{query.file.filename}}
not done
group by heading
```

`````

[muell-better-export-plugin-tasks-plugin.md](https://github.com/l1xnan/obsidian-better-export-pdf/files/14976094/muell-better-export-plugin-tasks-plugin.md)


![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4138869/6016a053-316c-477b-bb2e-933c29c57413)


(Has it something to do with the amount of time, your plugin waits for generating the file?)

(The built in pdf export of obsidian has no problems with generating any of the testfiles.)

**Comment by l1xnan** [comment]
An error occurs here when a link lacks the `href` attribute:
https://github.com/mdelobelle/obsidian_supercharged_links/blob/master/src/linkAttributes/linkAttributes.ts#L102-L103

**Comment by l1xnan** [comment]
> I don't know, if you can control this pagebreak inside the calendar output:

Essentially, it's a large table. Regarding the pagination issue with large tables, the underlying PDF engine doesn't handle it well. We need to rely on upper-level pagination algorithms to handle it. Estimating the workload for this part is quite significant, and I haven't come up with a good solution yet. Hopefully, it can be resolved in version 2.

**Comment by merlinuwe** [comment]
Good news, again: I can export the whole note with the tasks sequence.

Your change in supercharged links was successful, very impressive.

The only thing is, that the side before the output of the tasks plugin is empty.

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4138869/23ed20d2-5d8e-4672-97db-aa63d7acb24e)

(bokeh-effect only because of private data.)

**Comment by l1xnan** [comment]
> Good news, again: I can export the whole note with the tasks sequence.
> 
> Your change in supercharged links was successful, very impressive.
> 
> The only thing is, that the side before the output of the tasks plugin is empty.
> 
> ![image](https://private-user-images.githubusercontent.com/4138869/322425454-23ed20d2-5d8e-4672-97db-aa63d7acb24e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzMzMzcsIm5iZiI6MTcxMzE3MzAzNywicGF0aCI6Ii80MTM4ODY5LzMyMjQyNTQ1NC0yM2VkMjBkMi01ZDhlLTQ2NzItOTdkYi1hYTYzZDdhY2IyNGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTVUMDkyMzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzdhYmI3NWRlZTYxMjdkZWJkYjlhY2IyMWExNTIwOWQ3YjU0M2M5ZTFiY2NmMWQwYTlkOGE2YzkzYmNiN2MyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zJsYR5j39CYSDy-QQiDfraFWa1CvLIST7tfh-b3R7LA)
> 
> (bokeh-effect only because of private data.)

You might need to check the CSS properties to see if break-after is set.

https://developer.mozilla.org/en-US/docs/Web/CSS/break-after

**Comment by merlinuwe** [comment]
Thank you very much for making the pull request for supercharged links plugin.

---

I added something in the obsidian forum, because there are similar (but not the same) export issues with the native obsidian export:

https://forum.obsidian.md/t/pdf-export-of-tasks-not-all-tasks-are-in-the-exported-pdf-file/80375
