### ISSUE TITLE
当定义了锚点时，导出pdf，其中的链接不能正确显示

### ISSUE THREAD

**Issue by cytihuntor** [l1xnan/obsidian-better-export-pdf#173]
源码如下：

```
### commit<a name="commit" />

1. [这是一个链接](baidu.com)


```

输出结果如下：

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/9362545/d1f11004-ac16-4496-99b6-b3b4dd144103)

**Comment by l1xnan** [comment]
官方的导出功能有这个问题（目前插件遵循的标准和官方一致），可能这个在官方的渲染器看来是不合法的。
最好删除 `<a name="commit" />` 这一段

**Comment by cytihuntor** [comment]
应该是我搞错了，确实官方也不可以。谢谢！
