### ISSUE TITLE
拼写小建议

### ISSUE THREAD

**Issue by victorwwd** [l1xnan/obsidian-better-export-pdf#183]
...
“    new Setting(contentEl).setName("Downscale precent").addSlider((slider) => {”
...

这里的“Downscale precent”建议改成“Downscale percentage”或“Scaling ratio”

**Comment by l1xnan** [comment]
英语不好，抄官方的😂
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/4d979248-1000-4386-a9e0-8e13c757f3e0)

**Comment by l1xnan** [comment]
> 那你percent拼错啦

感谢，尴尬🤣
