### ISSUE TITLE
Bug: Fails to install update.

### ISSUE THREAD

**Issue by jmcd040** [l1xnan/obsidian-better-export-pdf#187]
Currently have version 1.7.4. Attempts to install update fail.
![Screenshot 2024-04-24 084146](https://github.com/l1xnan/obsidian-better-export-pdf/assets/44679831/249e6b6b-182c-45a6-b543-3e4a0ee77a8c)

**Comment by l1xnan** [comment]
Sorry, this may be because the 1.7.5 version was updated, but the corresponding package was not released. Now that version 1.7.5 has been released, you can try the update again.
