### ISSUE TITLE
Issue: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ShootingKing-AM** [l1xnan/obsidian-better-export-pdf#188]
- Select Folder -> Export to PDF -> .... wait for dom to load forever -> Check console to find the below error. 

Outcome: Cant export the folder. 
Expectation: Export whole folder into pdf

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4137788/82e8f766-3b4b-487e-a1be-198ecf12714b)

But rest everything seems to work fine. Notes folder is attached below

[TestNotes.zip](https://github.com/l1xnan/obsidian-better-export-pdf/files/15106370/TestNotes.zip) - There are unlinked pictures in this zip file since its going over github limit of 25MB i removed the pictures.

**Comment by l1xnan** [comment]
I added file log, can you replace the local plugin, first locate which note file caused:

[better-export-pdf.zip](https://github.com/l1xnan/obsidian-better-export-pdf/files/15108601/better-export-pdf.zip)

**Comment by ShootingKing-AM** [comment]
I dont know how to install the plugin from .zip. I attached my obsidian notes which gave me the error in the first post. 

If you try to export this folder ([folder](https://github.com/l1xnan/obsidian-better-export-pdf/files/15106370/TestNotes.zip)), you can reproduce the error on your machine.

**Comment by dleeftink** [comment]
@l1xnan It looks like a lot of btoa data in the encodedEmbeds function that was recently merged (possibly caused by multiple nested embeds, or a single large embed with many nodes). An interim fix would be splitting the btoa encoded strings if exceeding a certain length.

Although I think a more permanent fix would be loading the `printDoc` in the webview without serialising the HTML generated by the `MarkdownRenderer`.

**Comment by l1xnan** [comment]
> @l1xnan It looks like a lot of btoa data in the encodedEmbeds function that was recently merged (possibly caused by multiple nested embeds, or a single large embed with many nodes). An interim fix would be splitting the btoa encoded strings if exceeding a certain length or storing the nested nodes in a weakmap.
> 
> Although I think a more permanent fix would be loading the `printDoc` in the webview without serialising the HTML generated by the `MarkdownRenderer`.

The issue lies in the `String.fromCharCode` function. When the content is excessively long, it triggers the `RangeError: Maximum call stack size exceeded` error. Currently, focusing on optimizing the `btoa_utf8` function should resolve the issue.

**Comment by ShootingKing-AM** [comment]
Thanks for the fix @l1xnan . Can you release a minor version ? :3

**Comment by l1xnan** [comment]
> Thanks for the fix @l1xnan . Can you release a minor version ? :3

I have released a fixed version. Since I couldn't reproduce the issue using your note files, I'm not sure if there are any other issues.

**Comment by ShootingKing-AM** [comment]
Yup, updated and it works.
But a little slow, i guess.

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4137788/eae33f4a-3ab6-4e05-b76a-c0a653f40723)
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4137788/3d7801c3-96cf-4853-87c9-0cc4b1a2f087)

**Comment by l1xnan** [comment]
I have also noticed this slow problem, thought of a few areas that can be improved, and expect to complete it in the next minor release.

**Comment by ShootingKing-AM** [comment]
Sure, Thankyou. But its unrelated to this thread i guess. This particular issue is resolved :3
