### ISSUE TITLE
Page Ordering for Folder Export

### ISSUE THREAD

**Issue by OldManUmby** [l1xnan/obsidian-better-export-pdf#189]
When exporting a folder, it is grabbing the files in the wrong order, different from the numbered order I have them in the folder. Suggestions?

**Comment by l1xnan** [comment]
Exporting folders doesn't guarantee the order of files. You can use [custom-export](https://github.com/l1xnan/obsidian-better-export-pdf#custom-export) to manually specify the order first. Later, we can add a configuration option to sort by time or name.

**Comment by OldManUmby** [comment]
THX. I'll try the custom-export option.
