### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by jmcd040** [l1xnan/obsidian-better-export-pdf#190]
I know PayPal takes a cut, but I would support you financially if you allowed payment through them. I would also use Venmo, but I'm uncomfortable with other payment methods.

**Comment by l1xnan** [comment]
Thank you so much. I've updated my [Paypal.Me](https://paypal.me/l1xnan) in the [README](https://github.com/l1xnan/obsidian-better-export-pdf#support-this-plugin), as I've never really used Paypal before and I'm not sure if it works properly. It doesn't matter if it fails, Your use and recognition of this plugin is the best support for me.
