### ISSUE TITLE
Valid footer template produces unexpected results

### ISSUE THREAD

**Issue by carlgustavh** [l1xnan/obsidian-better-export-pdf#191]
My footer template:
```html
<div style="font-family: 'Latin Modern Roman', serif !important; font-size: 10pt !important; text-align: justify !important;">
  <span class="pageNumber"></span> / <span class="totalPages"></span>
</div>
```
My resulting footer:
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/95967108/44cee258-964d-47dc-b7e1-febbe2d61b72)

As you can see, the font is not exactly what I expected.

**Comment by l1xnan** [comment]
Make sure the system indeed has the Latin Modern Roman font, which might be under a different name. Additionally, you can first use a commonly used font to test whether the code snippet is effective. Example for:
```html
<div style="width: 100vw;font-size:10px;text-align:center;font-family:Cambria;"><span class="pageNumber"></span> / <span class="totalPages"></span></div>
```
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/1bc42c84-e677-4d6d-857b-0c11795108a9)

**Comment by l1xnan** [comment]
The actual font name:
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/a0d3e44f-ef27-4018-af84-e76a3bb9b63c)
