### ISSUE TITLE
请问，是否可以添加pdf最前面添加toc目录区？

### ISSUE THREAD

**Issue by xh542428798** [l1xnan/obsidian-better-export-pdf#192]
真的太感谢了，终于有了带书签导出pdf的插件了！这个插件真是太棒了，原始ob不支持带书签，真是太难受了。万分感谢大佬！！

想问一下，是否可以继续支持在导出的pdf最前端添加`[toc]`目录区：
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/49368033/3cdb46c4-d8ff-47cb-b8e9-0779d2949151)

**Comment by l1xnan** [comment]
这个插件专注于解决导出PDF的问题，它不会主动修改页面渲染结果，你可以使用其他插件（比如：https://github.com/johansatge/obsidian-automatic-table-of-contents ）来生成这个目录，通过插件导出的PDF也会保留目录的锚点，可以在页面内跳转。

**Comment by xh542428798** [comment]
> 这个插件专注于解决导出PDF的问题，它不会主动修改页面渲染结果，你可以使用其他插件（比如：https://github.com/johansatge/obsidian-automatic-table-of-contents ）来生成这个目录，通过插件导出的PDF也会保留目录的锚点，可以在页面内跳转。

了解了，非常感谢！
