### ISSUE TITLE
Feature Request: Single continuous page export

### ISSUE THREAD

**Issue by Asveste** [l1xnan/obsidian-better-export-pdf#197]
It would be nice if the option to export everything into one page could be added, meaning you would just get a single continuous long page. 
You can sort of already do it by setting custom height, but its very annoying to find out the exact height for every document. 
Some sort of "Endless/Continuous" option that automatically sets the right height to get everything into one single page would be awesome to have.

**Comment by l1xnan** [comment]
When adding the feature for custom page sizes, I intended to support this feature. However, I ultimately found that I couldn't accurately determine the width and height of the page. Therefore, I gave up on it and only added a feature to prompt the user for page size (though it's also a half-baked feature). This allows users to manually adjust based on the prompt. This feature can be continuously optimized in the future.
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/d56605cf-c1ee-403d-b430-7539fcdddd7b)

**Comment by teamolhuang** [comment]
Is the size hint still there? Using 1.9.2 I don't see it on preview.

**Comment by l1xnan** [comment]
It will be displayed only when the `Page size` is `Custom`.

**Comment by teamolhuang** [comment]
> @teamolhuang It will be displayed only when the `Page size` is `Custom`.

My bad, it did show up when I switch to Custom. Thanks!
