### ISSUE TITLE
图片超过A4纸的大小会被截断

### ISSUE THREAD

**Issue by STHxiao** [l1xnan/obsidian-better-export-pdf#2]
图片超过A4纸的大小会被截断，而不像typora那样可以续延到下一页

**Comment by l1xnan** [comment]
官方导出功能有截断现象么?

**Comment by STHxiao** [comment]
没有的

**Comment by freemankevin** [comment]
是我不会用还是这个插件压根就没用，我的obsidian 是最新版的，感觉没有啥效果，我想要typora 那种导出PDF 自带书签/导航栏/侧边栏的效果，目前都没有一款插件可以做到，真心遗憾。

**Comment by l1xnan** [comment]
@STHxiao @freemankevin 
能提供下样例文件么?

**Comment by freemankevin** [comment]
```markdown 

## Section 1 <a name="section-1"></a>

In Obsidian, you can create bookmarks using the Markdown link syntax. These bookmarks are typically treated as bookmarks in PDF or HTML files by other Markdown editors or transformation tools (such as Pandoc).

The common practice is to add an HTML tag to the portion you want to mark. You can use HTML syntax directly in Markdown. Here's an example:

```bash
sudo apt-get install pandoc
```


## Section 2 <a name="section-2"></a>

Finally, although the Markdown syntax itself does not directly support bookmarks, the wonderful flexibility of Markdown allows for mixing HTML tags, and we can leverage this capability to introduce features like bookmarks. However, be aware that this method may not work if your Markdown file will be used in an environment that doesn't accommodate HTML.

```bash
pandoc your-note.md -o output.pdf --from markdown --template eisvogel --listings
```



## Section 3 <a name="section-3"></a>

In this example, <a name="section-1"></a> is an HTML anchor tag, where name="section-1" defines its identifier. You can then reference this tag using the Markdown link syntax:


[Go to Section 1](#section-1)

When you click this link, the page scrolls to the anchor point with the identifier section-1, i.e., "Section 1".

Then, when you use another tool (like Pandoc) to convert the Markdown to PDF or HTML format, these bookmarks, as they are essentially HTML links, are typically also converted to PDF or HTML bookmarks.

Be sure to use the correct settings and parameters when converting, as different tools and settings may affect the generation of bookmarks. For example, you may need to use the --toc parameter in Pandoc to generate a table of contents.



```

**Comment by l1xnan** [comment]
@freemankevin 没有问题呀
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/07dfbdca-da38-4272-8d81-c9307afd417a)

**Comment by freemankevin** [comment]
??? 我这边怎么不行？

**Comment by freemankevin** [comment]
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/71524776/cbc59bdd-d62b-46c7-b844-1a92e5d8e2b7)
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/71524776/bc380ac6-02a8-429a-9b1b-7dd70e812578)
需要特殊设置？？？

**Comment by l1xnan** [comment]
@freemankevin 你是不是用的官方自带的`导出为PDF`，而不是插件的 `Better to PDF`？

**Comment by freemankevin** [comment]
> @freemankevin 你是不是用的官方自带的`导出为PDF`，而不是插件的 `Better to PDF`？

是啊，还有其他方式导出？

**Comment by l1xnan** [comment]
@freemankevin 
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/4a02f540-3946-419b-97c9-9676d2a40dc8)

**Comment by freemankevin** [comment]
OK，确实可以，干得好，谢谢。

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/71524776/b9769026-f69c-4abe-8b4c-5b98f4973f61)
