### ISSUE TITLE
How to custom font-family for page header and footer

### ISSUE THREAD

**Issue by Least-Action-Frank** [l1xnan/obsidian-better-export-pdf#211]
Thank you for your great efforts to gennerate this amazing plugins.
Following up hint specified "readme", I try to add font-family in Advanced setting, but it doesn't work. Actually I input "font-family:"simkai";", but it seems still default font to be generate in PDF file.

**Comment by l1xnan** [comment]
Font file names may not necessarily be the actual system font names. The font may not be called `simkai`? `楷体`?

**Comment by Least-Action-Frank** [comment]
Thank you for kind advice, you are right. This problem is caused by wrong using in quotation mark.
Again thank you.
