### ISSUE TITLE
Paragraph Indent

### ISSUE THREAD

**Issue by Least-Action-Frank** [l1xnan/obsidian-better-export-pdf#213]
By use one snippet (refer to code hereinafter) Paragraph Indent for Chinses is relized both in edit and reading. But export PDF, Paragraph Indent is missing in generated PDF.

/* === 段落-首行缩进2个字符 By Linzeal 2024/2/1更新  yuanling 2024/03/30 改=== */

/* 也包括段落中每个回车换行后的首行缩进 */

:is(
.markdown-source-view .cm-line:not(:is(:has(>.cm-hmd-frontmatter,>br),.HyperMD-header,.HyperMD-list-line,.HyperMD-quote,table .cm-line)), /* 编辑模式 */
.markdown-rendered :not(:is(blockquote)) >  /* 阅读模式 text-indent不支持each-line的办法 */
){
  text-indent: 2em !important;
}

/*若支持each-line参数则用这个即可，更为简单，就无需下面的修正 */

/* 阅读模式下对每个回车换行后的首行缩进的修正 */
/*需要 contextual tyopgraphy 插件*/

.markdown-rendered div[class*="el-p"]:not(blockquote) > p
{
  text-indent: 2em;
}

.markdown-rendered div[class="el-p"]:not(blockquote) > p>br {
  content:'';
  white-space:pre;
}
.markdown-rendered div[class="el-p"]:not(blockquote) > p>br::after {
   content:'\000A\2004\2004\2003';
}

/* === CSS代码结束 === */

**Comment by l1xnan** [comment]
官方的导出PDF功能是否生效？

**Comment by Least-Action-Frank** [comment]
这是Obsidian编辑区及生成的PDF文件的截图
![捕获1](https://github.com/l1xnan/obsidian-better-export-pdf/assets/136563423/f23d89d9-fbbf-4510-87a2-c1224c7964c0)
![捕获2](https://github.com/l1xnan/obsidian-better-export-pdf/assets/136563423/d8d3f6c8-3d71-48ca-900b-a4fefc36bf30)

**Comment by l1xnan** [comment]
是不是预览模式也没有首行缩进呀? 我看官方导出的 PDF 也没有首行缩进，当前插件底层实现是和官方一致的，所以效果也一样。是不是上游插件对这个场景适配有问题?

**Comment by Least-Action-Frank** [comment]
是的，预览模式也没有首行缩进。应该是您分析的原因造成的，可由于我没有这方面的知识，不是如何解决。方便的话能否分享一点有助于解决这种问题的知识文档。
非常感谢耐心的帮助。

**Comment by Least-Action-Frank** [comment]
收到，感谢如此细致的解答。
