### ISSUE TITLE
[small bug] Custom styles applied to <strong> and <em> are getting reset to their defaults

### ISSUE THREAD

**Issue by AdamFipke** [l1xnan/obsidian-better-export-pdf#219]
I have some custom styles that change the colour of `**bold**` and `*italic*` text to orange.

This works fine in obsidan's default "export to pdf" feature (picture below)
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/13655728/c3c5d6c3-bcbe-443d-838b-c6bcdb52703d)

However, when using this plugin, these colours are removed (picture below).
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/13655728/300eda77-a379-4475-b63c-89bc005a2c18)

Though, these styles can be re-applied by using the custom CSS.
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/13655728/4b4db10b-c65f-4cb9-9af1-02dd5daf2840)
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/13655728/5644ce3e-ea84-4685-beb9-91f5cb936bde)

**Comment by AdamFipke** [comment]
i managed to do a temporary workaround by doing some inline CSS like so:
`<span style="color: rgb(255, 138, 120); font-weight:600">Produce Clerk</span>`

**Comment by AdamFipke** [comment]
update: I thought that using the custom CSS wouldn't work, but it just turns out i was using CSS wrong and applied the rgb value in the wrong way. So, the severity of this issue isn't nearly as big as i thought it was, and now it's only a minor inconvenience to re-apply the proper CSS

**Comment by l1xnan** [comment]
First, make sure that the CSS code snippet is enabled by default; otherwise, you'll need to select it within the export modal. Then, you can enable `Debug` mode to see which CSS snippet is actually taking effect.
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/fe9b1075-386c-45fb-80b5-2b4ed4e5129d)

**Comment by AdamFipke** [comment]
Oh I see that's what the debug button does!

Ah hmm it seems like obsidian's default stylesheet (?) is overwriting any set --bold-color
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/13655728/77cc775a-d242-4ae5-98d2-35a95a69e0b7)

Disabling this line makes it appear properly
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/13655728/cdf13c80-a89f-4ad0-83b8-97b5ccfd8d16)
This is where the colour is defined.
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/13655728/db988562-d69a-497c-8383-4dc9310e5d99)

This might just be a weird interaction between the [Border theme](https://github.com/Akifyss/obsidian-border) I use and this plugin 

Anyways yeah it was pretty easy to fix by just using a custom CSS stylesheet for exporting, i'll close the issue since this is probably a rare, inconsequential bug and not worth investigating
