### ISSUE TITLE
打开插件后不显示预览也不能导出

### ISSUE THREAD

**Issue by 1538379200** [l1xnan/obsidian-better-export-pdf#222]
开始导出是没有问题的，能正常导入，内容比较少，但是等写完后，就不能导出了，一直在预览界面，什么提示也没有，点击导出显示 `dom not ready` 
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/42434762/d475d039-3270-4d45-8919-9a564117aeed)

使用内置的导出没有问题，导出的速度很快，内置的导出显示的 pdf页面也只有 13 页
页面中使用了 `table of content` 插件做了目录

**Comment by l1xnan** [comment]
看一下 console 有啥报错没？

**Comment by 1538379200** [comment]
试了一下，我估计可能是 `table of content` 插件导致的错误，在设置了标题颜色后，导致出现不是有效链接的错误，虽然链接是正常的

**Comment by l1xnan** [comment]
跟踪 https://github.com/l1xnan/obsidian-better-export-pdf/issues/229
