### ISSUE TITLE
RTL support 

### ISSUE THREAD

**Issue by David-Pinhasov** [l1xnan/obsidian-better-export-pdf#228]
Hello Lee

When I export to PDF everything is left aligned.
I'm not using the RTL build in option that obsidian has developed. 
Instead, I'm using "RTL Support" becuase it keeps every language at his own direction. Exporting to pdf with "RTL Support" 
plugin has no problems (in 1.2.1 version). 

![obsidian example](https://github.com/l1xnan/obsidian-better-export-pdf/assets/112503898/0350630e-eed7-4f0a-b085-87d0b52cc570)

**Comment by David-Pinhasov** [comment]
Version 1.6.3 was released. It seems the problem has been fixed

**Comment by l1xnan** [comment]
That's great! I noticed that one of the highlights of the 1.6 version update is improved RTL support. Thank you for your feedback!
