### ISSUE TITLE
如何修改Header 和Footer模板的字体/颜色/形式？

### ISSUE THREAD

**Issue by bakebakebakebake** [l1xnan/obsidian-better-export-pdf#231]
如题，直接加上页眉和页尾感觉比较突兀，我如何设置成像Word文档的页眉和页尾的形式呢？

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/119475415/add88205-2655-4397-b3bd-298999f023f0)

像这样
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/119475415/91104062-be7d-4941-b61b-a824f05de635)

想要变成灰色且有个边框做区分，这样能做到吗？🤔

**Comment by l1xnan** [comment]
可以参考这个 issue: https://github.com/l1xnan/obsidian-better-export-pdf/discussions/130
