### ISSUE TITLE
导出PDF，如果图片不是本地而是图床上的图片时，导出会特别慢

### ISSUE THREAD

**Issue by KodoShinichi** [l1xnan/obsidian-better-export-pdf#25]
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/26167263/48c3fa3b-0322-40c5-a5d5-0f151cc32ee1)

而官方的很快就导出了

**Comment by l1xnan** [comment]
插件的原理是把内容放到 webview 标签中，所有远程资源重新加载，dom 要重新渲染一遍，这上面会耗费点时间，为了防止异常，中间又加了 5s 的等待，所以显得有点慢，后面会做一点优化，添加一些进度提示之类的信息

**Comment by l1xnan** [comment]
新版本逆向实现了官方的打印函数，速度上有很大优化，可以试用下看看
