### ISSUE TITLE
Export block links within a file

### ISSUE THREAD

**Issue by ryanjamurphy** [l1xnan/obsidian-better-export-pdf#254]
Thanks for this plugin. Incredible work! I am supremely grateful.

One thing that doesn't work yet is block links. E.g., if I have a block:

```markdown

Some text! ^myblock
```

And then I have a link later in the file:

```markdown
A link to [[#^myblock]].
```

Better Export PDF doesn't export that as a link (though the text is still styled as a link).

Running Obsidian 1.6.5, Better Export PDF v. 1.8.1.

🙇‍♂️ Thanks again!

**Comment by l1xnan** [comment]
I tested the example you gave. The link can be jumped. Can you test to open your Debug mode and check if the `blockid` rendering is normal?
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/91a21305-3ffa-4e59-9a8b-ad4f4cf9cc20)

**Comment by ryanjamurphy** [comment]
D'oh, should have tested my own demo. The actual problem I'm having is a block id for a callout, which perhaps is already covered by https://github.com/l1xnan/obsidian-better-export-pdf/issues/100#issuecomment-1916706283

`blockid` in the target seems to render properly in the DOM, but the link does not:

![CleanShot 2024-07-09 at 12 50 56](https://github.com/l1xnan/obsidian-better-export-pdf/assets/3618647/59299019-f46f-4e38-ac33-3ecd30db22ae)


![CleanShot 2024-07-09 at 12 50 17](https://github.com/l1xnan/obsidian-better-export-pdf/assets/3618647/d4318e01-66db-4911-86c0-0a16f1658aef)


Here's what's failing for me. The target:

```markdown

> [!OUTCOME]+ Use principles and frameworks to make ethical decisions about information systems and knowledge management issues in organizations.
> 
> - [ ] 📖 Read the introduction and chapter 1 of Mike Monteiro's _Ruined by Design_ %% [@Monteiro2019Ruined-By-Design-How-Designers, introduction and chapter 1] %%
> - [ ] 📖 Review the Canadian guidelines to security and privacy of information
> - [ ] 📖 Review the ethical lenses reading
> - [ ] 📚 [[#Topic exams]]
> - [ ] ✍️ [[#Applied reflections]]: [[#Ethical Information Systems]]
^MGMT-6006-LO-5-1

```
...and the link:
```markdown
#### Ethical Information Systems

> [!OUTCOME] Week 11
> - [ ] [[#^MGMT-6006-LO-5-1]]

Review and respond to the chosen case study.
What are the ethical dilemmas in the case?
What should the organization do? Why?
```

Perhaps it is case-sensitive?

**Comment by l1xnan** [comment]
I haven't seen a situation where the `blockid` is in uppercase. Obsidian should have made the conversion, but I didn't convert it, which caused this problem. It will be fixed in the next version. For now, we can only uniformly use lowercase to solve this issue.
