### ISSUE TITLE
Internal link to note is being displayed multiple times

### ISSUE THREAD

**Issue by heykapil** [l1xnan/obsidian-better-export-pdf#259]
Hi there,

This plugin is generating internal link text multiple times. Look at the internal link (Holomorphic) in the first theorem as in screenshots.

Here is the source code

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/101615305/5aecfbd3-16ec-40ba-b252-d6510a0e16ad)

**Reading view:**

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/101615305/e76d9a12-5786-44e4-92cb-4ef6a277f7af)

**Plugin preview and settings for export**

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/101615305/f731f05d-c6e0-4d8d-a64f-36905bfe317f)

**PDF generated:**

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/101615305/c79dc1a5-fce0-4d98-bc3a-d553e1dfcda6)

The default pdf export plugin is working fine and not generating multiple internal links like above mentioned.

## Debug Info:

SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.3
	Operating system: Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:12 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8103 23.1.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Things
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 28
	Plugins enabled: 28
		1: Formatto v1.2.7
		2: Completr v3.2.0
		3: Auto Front Matter v2.0.2
		4: MAKE.md v0.9.31
		5: Linter v1.24.0
		6: LanguageTool Integration v0.3.7
		7: Various Complements v10.0.0
		8: Latex Suite v1.9.4
		9: WordWise v0.7.4
		10: Image Layouts v0.15.4
		11: TikZJax v0.5.2
		12: Better MathJax v1.0.1
		13: Extended MathJax v0.4.1
		14: Git v2.24.3
		15: Copilot v2.5.2
		16: Consistent Attachments and Links v1.3.0
		17: Note Linker v1.2.4
		18: Todoist Sync v1.13.0
		19: Obsidian Columns v1.5.2
		20: No more flickering inline math v0.3.5
		21: LaTeX-like Theorem & Equation Referencer v2.2.0
		22: MathLinks v0.5.3
		23: CSS Editor v1.2.1
		24: Admonition v10.3.2
		25: Reference Generator v1.0.1
		26: MagicCalendar v1.1.9
		27: Markmind v2.0.1
		28: Better Export PDF v1.8.2

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by l1xnan** [comment]
Could you provide the Markdown file for reproducing this issue?

**Comment by heykapil** [comment]
Here is the markdown file for reproduction of issue.

https://notes.kapil.app/Taylor%20Theorem.md

Internal Link to this markdown file: https://notes.kapil.app/Holomorphic%20and%20Meromorphic%20functions.md


The html debug file (during print)which is causing the repetition of the internal links is:

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/101615305/521fbfbc-75ba-4e0a-a091-49261b9bf94b)

This one and the [Mathlinks](https://github.com/zhaoshenzhai/obsidian-mathlinks) plugin causing compatibility issues, however the built-in PDF export feature of Obsidian appears to be functioning properly. For now, this custom CSS is fixing problem for me temporarily.

```css
a.mathLink-internal-link {
display: none !important;
}

a.original-internal-link { 
display: inline !important;
}
```
