### ISSUE TITLE
cann't export pdf expect first time no scale

### ISSUE THREAD

**Issue by kctekn** [l1xnan/obsidian-better-export-pdf#261]
cann't export pdf expect first time no scale:
![issue](https://github.com/user-attachments/assets/7e3db113-d6e4-4652-be83-642e112d0878)
after that , no matter how you change the scale, it will not work.

**Comment by l1xnan** [comment]
It might be that the historical configuration file of the plugin is abnormal. Try to delete the configuration file `data.json` of the plugin.

**Comment by Hongchao-Zhang-PUMC** [comment]
> It might be that the historical configuration file of the plugin is abnormal. Try to delete the configuration file `data.json` of the plugin.

Thanks a lot! Problem solved.
