### ISSUE TITLE
the plugin exports plotly charts as native yaml markdown text - not rendered as charts

### ISSUE THREAD

**Issue by Bakr2030** [l1xnan/obsidian-better-export-pdf#266]
i use this plugin extensively, (https://github.com/Dmytro-Shulha/obsidian-plotly)
and better-pdf-export does not support the rendered output of that plugin.
what i do, is export as HTML, and then copy paste manually into MSWORD, and then convert to PDF.
I hope this plugin to support plotly

this is a sample plotly markdown

```plotly:
  data:
    - type: scatter
      mode: lines+markers
      x: [2027, 2028, 2030, 2034]
      y: [184.8, 348.25, 840.7, 1496.25]
      name: "Net Income ($M)"
      line:
        color: "#FFA15A"
  layout:
    title: "Yearly Profitability Projections"
    xaxis:
      title: "Year"
    yaxis:
      title: "Net Income ($M)"
```

**Comment by l1xnan** [comment]
I haven't reproduced this issue. Which version of the plugin are you using? Are there any error reports when you open the developer tools?  
![image](https://github.com/user-attachments/assets/99d662c9-ef0f-4b56-9533-5c82abab0529)

**Comment by Bakr2030** [comment]
Thank you very much, i have discovered the issue as follows:

in the plotly code block it as like this

``plotly:

  rest of yaml markup.....

``

i have fixed by removing the ":" after plotly

``ployly
 
 rest of yaml markup

``

now the pdf is rendering properly
