### ISSUE TITLE
打印表格时最后一行表格无法正确渲染

### ISSUE THREAD

**Issue by Alex-coder251** [l1xnan/obsidian-better-export-pdf#269]
![image](https://github.com/user-attachments/assets/200c4838-ea1a-4710-b3f6-5c3d51aae2de)

ob自带的导出就没这个问题，请问这个可以修好吗？感谢大大的贡献

**Comment by l1xnan** [comment]
表格中是不是有 blockid， 问题文件可以分享下不？

**Comment by Alex-coder251** [comment]
[海洋科学名词解释.md](https://github.com/user-attachments/files/16385851/default.md)
我这个表格是利用dataview生成的然后复制过来的， 应该没有blockid

**Comment by l1xnan** [comment]
表格中间有个 blockid `^3adunb` 造成的，插件对表格中间的 blockid 有点问题

**Comment by Alex-coder251** [comment]
谢谢大大💕
