### ISSUE TITLE
1.9.0 版本 大纲存在问题，，，最顶端会多出一个大纲标签

### ISSUE THREAD

**Issue by entps** [l1xnan/obsidian-better-export-pdf#282]
1.9.0 版本 大纲存在问题，，，最顶端会多出一个大纲标签

**Comment by l1xnan** [comment]
不设置 `将笔记名作为标题` 的时候么？

**Comment by entps** [comment]
是的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月07日 11:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [l1xnan/obsidian-better-export-pdf] 1.9.0 版本 大纲存在问题，，，最顶端会多出一个大纲标签 (Issue #282) |

不设置 将笔记名作为标题 的时候么？
