### ISSUE TITLE
Error: Invalid print parameters: scale is outside of [0.1 - 2] range

### ISSUE THREAD

**Issue by Midorina** [l1xnan/obsidian-better-export-pdf#296]
Hello,

I choose 100 downscale percent and try to export. However, I get the error in the title.

![image](https://github.com/user-attachments/assets/2b3ca9b0-cd80-463f-87e7-0afa4d34f6b4)
![image](https://github.com/user-attachments/assets/2c3356af-16e2-4fba-953a-f1ba0490a0f2)
![image](https://github.com/user-attachments/assets/9116670e-9033-42fe-b7c8-2d41bb14c576)

**Comment by l1xnan** [comment]
It seems that there is no problem with the parameters. Restart Obsidian to see if the problem still exists?

**Comment by Midorina** [comment]
> It seems that there is no problem with the parameters. Restart Obsidian to see if the problem still exists?

Restarting Obsidian helped. That's very weird. Thanks a lot!
