### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by 1lazyprogrammer** [l1xnan/obsidian-better-export-pdf#300]
Hi I1xnan,

I hope you're doing well.

I'm having an issue with your Better PDF Export Plugin. The Custom CSS doesn't seem to work for me anymore. I've enabled the option in the settings (see attached picture), but I can't apply the Custom CSS when I try to export the file (see attached picture).

Is this a bug, or is it just an issue on my end? Do you have any suggestions on how I could fix this?

Thank you in advance for your help.

Best regards,

![Screenshot 2024-08-26 145806](https://github.com/user-attachments/assets/11a5f900-97a0-47f0-8cab-80fa676b1497)
![Screenshot 2024-08-26 150258](https://github.com/user-attachments/assets/feec6970-4765-496d-bb6b-cead9d2d0d58)

**Comment by l1xnan** [comment]
If all your custom CSS snippets have been enabled, the option to select CSS snippets will not be displayed on the preview page at this time, because it is meaningless.
