### ISSUE TITLE
Not exporting anymore

### ISSUE THREAD

**Issue by Monolecte** [l1xnan/obsidian-better-export-pdf#321]
Hi I1xnan,

Maybe it's since the new update, but the pluggin doesn't export at all.
I still have the export preview and the choice of file destination, but then nothing.

The debug mode gives me this output:

```
Uncaught (in promise) ReferenceError: electron is not defined
    at help.js:1:244286
    at window.ready (enhance.js:1:13136)
    at help.js:1:237433
    at help.js:1:1732
    at Object.next (help.js:1:1837)
    at i (help.js:1:555)
```

Best regards,

**Comment by l1xnan** [comment]
This error doesn't need attention. Besides this, are there any other error messages? Does it display the preview normally?

**Comment by Monolecte** [comment]
I don’t find any other error messages (but maybe there are some I don't know how to find).
I can see the preview, but it doesn't really seem to change when I change the parameters. Displaying or not displaying the title refreshes the preview, but changing the scale has no effect.

And there is absolutely no file export.

As far as I'm concerned, it doesn't work at all.

I'm running Debian 12 up to date.
Obdsidian is up to date.
Pandoc is installed and up to date.

Otherwise, I really like your pluggin... when it works.

**Comment by l1xnan** [comment]
The plugin does not depend on pandoc. You can troubleshoot the problem in the following ways: 
1. Delete the data.json configuration file of the plugin. 
2. Press `Ctrl+Shift+I` to open the developer tool and see if there are any errors.

**Comment by Monolecte** [comment]
Well done !
It’s working again !

Great thanks
