### ISSUE TITLE
[feature request] Page Break Control

### ISSUE THREAD

**Issue by midstreeeam** [l1xnan/obsidian-better-export-pdf#325]
Hi, thanks for the awesome plugin!
I’ve been using it for a while, but I’ve found it challenging to control where the page breaks occur during export. The export preview doesn't currently indicate where a new page will start, making it difficult to manage page layout.

It would be very helpful if there were a way to manually control where a new page begins. For example, adding a keyword or option to insert a page break at specific points in the content (e.g., before a custom html tag) would be great.

In my specific use case, I’d love to be able to automatically start a new page at each `<h2>` tag. 
Thank you for considering this feature!

**Comment by midstreeeam** [comment]
Nevermind, just found out that I can add `<div style="page-break-after: always;"></div>` easily to break the page. 
吃了文化的亏

**Comment by NaeemBolchhi** [comment]
```
@media print {
  hr {
	  break-after: page;
	  visibility: hidden;
  }
}
```

We can use this as a snippet to use horizontal lines as page breaks. This way, there's no need for html code in the document. The three dash `---` horizontal rule becomes a page break when saving the pdf.

**Comment by BigChickenLegs** [comment]
Is it possible to add settings or manual operation to control paging for each part when using ToC for multi-file export?

**Comment by aubreyz** [comment]
+1 to this. It would be nice to have a toggle to force a page break at the start of each note in a multi-note pdf if the user wants.

**Comment by l1xnan** [comment]
@BigChickenLegs @midstreeeam add css snippets:
```css
@media print {
  section {
    break-after: page;
  }
}
```
