### ISSUE TITLE
此插件失效(无法导出) | Unable to export 

### ISSUE THREAD

**Issue by MrTakizawa** [l1xnan/obsidian-better-export-pdf#327]
我不知道这是不是我一个人的问题，我今天写了一个md文件，然后点击Better Export PDF，插件的导出界面倒是能出来，各种设置也可以设置，但是设置完点击Export之后导出界面消失，PDF也没有成功导出，也没有弹出来什么ERROR报错，我不知道为什么会这样。

I don't know why I just can't use this plugin to export PDF. When I opt to the "Better Export PDF" and then click the "Export" button, nothing happens.

**Comment by l1xnan** [comment]
`ctrl+shift+i` 查看开发者控制台是否有异常报错.
尝试删除插件的 `data.json` 后重新导出

**Comment by MrTakizawa** [comment]
感谢，似乎真的只是我的问题。今天打开obsidian又试了一下是可以正常导出的，感谢作者
