### ISSUE TITLE
一点小问题(不知能否解决) - 文档属性-author-选为列表类型的时候无法导出PDF

### ISSUE THREAD

**Issue by MrKyomoto** [l1xnan/obsidian-better-export-pdf#328]
文档属性-author-选为**列表类型**的时候无法导出PDF，报错内容为：

TypeError: `author` must be of type `string`, but was actually of type `NaN`

这就是我之前PDF无法正确导出的原因

因为文档属性是我默认快速添加的，没想到不知道为什莫自动添加的author是列表类型而不是文本类型
![image](https://github.com/user-attachments/assets/b881d9cc-7624-4612-9019-d71088a3e7ea)
改为文本类型之后便可正常导出

也不知道这算不算BUG，主要是这种小问题导致的无法导出不会弹出来ERROR，只能去控制台查看报错内容

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
