### ISSUE TITLE
Send PDF as e-mail

### ISSUE THREAD

**Issue by jockie** [l1xnan/obsidian-better-export-pdf#335]
Great work, thank you very much!
I would love to see a functionality to attach the exported PDF to a new mail using the system's default mail client.

**Comment by l1xnan** [comment]
This plugin is currently only focused on exporting PDF files. At present, only PDF can be exported first, and then subsequent steps need to be manually processed.

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
