### ISSUE TITLE
How to print PDF with HTML <span> tag color-background effect INSIDE A TABLE

### ISSUE THREAD

**Issue by arieltutu** [l1xnan/obsidian-better-export-pdf#346]
First off, thank you for this fantastic plugin! It’s a huge help, especially since exporting notes to PDF with emoji or Twemoji via Pandoc can be quite complicated and doesn’t always work as expected. Additionally, maintaining outline structure in PDF is really convenient. 
I'm a programming noob. From what I understand, Pandoc converts Markdown to LaTeX (which lacks native emoji support) before generating a PDF, which often causes issues. See Pandoc official description: https://pandoc.org/MANUAL.html#creating-a-pdf

---

In plugin settings, I have toggled on "Print Background" already.
### My Problem:
So I try to export my note with HTML `<span>` tag code that include inline text with multiple background colors **inside a table**. Well, `<span>` background-color works fine with plain text, but not within a table after exporting. Here’s how it looks in the Obsidian preview:
  ![{F08FEB92-C632-4421-B104-60CF34FA847F}](https://github.com/user-attachments/assets/c759c039-0d53-4fb0-8cea-8c6f909f0e65)
  _P.S._: I tried using `<mark>` tags instead, but it only highlights text with a single background color (yellow) rather than multiple colors after rendering or exporting:
  ![{67BD201A-F540-4427-ADED-6B047EDAEFEB}](https://github.com/user-attachments/assets/027a0585-469d-4cad-b069-f05bbcd6662e)

---
### Question:
Is it correct to assume that `<span style="background-color: ...">` **type anything** `</span>`is unsupported **inside a tale** in the export?
  My obsidian source mode:
    ![{502195D9-E66F-4210-9A12-7DF8EC614456}](https://github.com/user-attachments/assets/9ad923d8-e2e8-446d-afd4-1da67fe253eb)

Here is what I get after `<span>` backgoud-color typing exporting:
  ![{89371763-455F-41CC-960B-836D59198942}](https://github.com/user-attachments/assets/1d214d80-89d1-4780-8f83-66e956033b01)

Or if there are any possible solutions I can get to display inline text background colors **inside a table**?

**Comment by arieltutu** [comment]
I also tried this [Emoji from Obsidian markup to LaTeX via Pandoc #193](https://github.com/OliverBalfour/obsidian-pandoc/issues/193), but it didn't work for me.

**Comment by arieltutu** [comment]
I also tried converting the note to HTML first and then to PDF, but it resulted in the **outline** structure being lost, which is not what I'm looking for.

**Comment by arieltutu** [comment]
谢谢啦 zfb支持了一下 😄

**Comment by l1xnan** [comment]
太客气了，感谢支持！Markdown 笔记文件是支持 HTML 片段的，背景颜色可以正常显示，没有复现你的问题，能提供下样例文件么?
```markdown
New para<font color="#e36c09">graph</font>

| Header1                                        | Header2 |
| ---------------------------------------------- | ------- |
| 🐸R1C1                                         | R1C2    |
| 🐱<span style="background:#ff4d4f">R2</span>C1 | R2C2    |
| 🐹R3<span style="background:#ff4d4f">C1</span> | R3C2    |
```
![image](https://github.com/user-attachments/assets/85994e49-07b2-4928-bd1b-05cc9245ac8d)

**Comment by arieltutu** [comment]
### Highlights, annotations

| highlights, annotations                                   | tags                                                                                                                                                                                                                                                           | text                                                                                                    |
| --------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------- |
| <mark>gold</mark>                                         | 👁️‍🗨️<span style="background-color: #FFF3A3A6;">discern</span><br>🪙<span style="background-color: #FFF3A3A6;">Standard</span>                                                                                                                               | <mark>highlight</mark>                                                                                  |
| <span style="background-color: #FF5582A6;">red</span>:    | 🆚<span style="background-color: #FF5582A6;">comparison, contrast</span>                                                                                                                                                                                       | ❌<span style="background-color: #FF5582A6;">False</span><br><font color=red>contrast, comparison</font> |
| <span style="background-color: #BBFABBA6;">green</span>:  | ⚕<span style="background-color: #BBFABBA6;">condition</span><br>🩺<span style="background-color: #BBFABBA6;">diagnosis</span><br>💉<span style="background-color: #BBFABBA6;">Treatment</span><br>♻<span style="background-color: #BBFABBA6;">mechanism</span> | ✅<span style="background-color: #BBFABBA6;">True</span>                                                 |
| <span style="background-color: #ABF7F7A6;">cyan</span>:   | 🔤<span style="background-color: cyan">EngTerm</span>                                                                                                                                                                                                          | <font color="#4bacc6">English terminology<br>terminology                                                |
| <span style="background-color: #D2B3FFA6;">purple</span>: | 🔢<span style="background-color: #D2B3FFA6;">statistics</span><br>🚪<span style="background-color: #D2B3FFA6;">threshold</span>                                                                                                                                |                                                                                                         |
| <span style="background-color: #FFB8EBA6;">pink</span>:   | 🧠<span style="background-color: pink">Mnemonics</span>                                                                                                                                                                                                        | <font color= magenta>~abstract</font>                                                                   |
| <span style="background-color: #FFB86CA6;">orange</span>: | 🔑<span style="background-color: orange">KEY POINT</span><br>comparison                                                                                                                                                                                        | <span style="background-color: #FFB86CA6;">review</span>                                                |
| <span style="background-color: #CACFD9A6;">grey</span>:   |                                                                                                                                                                                                                                                                | 🗒<font color="#a5a5a5">descriptions, insinuations                                                      |
| **black**:                                                |                                                                                                                                                                                                                                                                | ✒text                                                                                                   |


<!--HTML, Markdown -->

**Comment by l1xnan** [comment]
@arieltutu 没有复现，奇怪
![image](https://github.com/user-attachments/assets/661e3a67-8616-4b7d-9342-f4b367ed53c1)

**Comment by arieltutu** [comment]
> @arieltutu 没有复现，奇怪 ![image](https://private-user-images.githubusercontent.com/6105390/384297172-661e3a67-8616-4b7d-9342-f4b367ed53c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDk2MTQsIm5iZiI6MTczMjEwOTMxNCwicGF0aCI6Ii82MTA1MzkwLzM4NDI5NzE3Mi02NjFlM2E2Ny04NjE2LTRiN2QtOTM0Mi1mNGIzNjdlZDUzYzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjBUMTMyODM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODhmODRlZDdmNzNiOWEwZjg3OGYxNTQ4ZGQwMTE2NWQ4ZTJmN2UwZDRmYmJmODk0MDhlODdiODEzYWFkNGJjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ihJBXJ1Hs_ZXa0uNa9X5eys6mVBi5V_dOrwRTx-xKEk)

排查了一下 应该是我装这个表格插件的原因 [Sheets Extended](https://github.com/NicoNekoru/obsidan-advanced-table-xt) 关掉就可以打印了

**Comment by PlayerMiller109** [comment]
不知道你的问题解决了吗。你也可以用这个帖子 https://forum-zh.obsidian.md/t/topic/35091/1 介绍的插件。我顺便试了一下带合并的能否正常打印，也是没有问题的。记得看说明哦。

<img width="400" src="https://github.com/user-attachments/assets/89c24be4-54d9-487e-bf3e-d4947f496d52">

**Comment by arieltutu** [comment]
> 不知道你的问题解决了吗。你也可以用这个帖子 https://forum-zh.obsidian.md/t/topic/35091/1 介绍的插件。我顺便试了一下带合并的能否正常打印，也是没有问题的。记得看说明哦。
> 
> <img alt="" width="400" src="https://private-user-images.githubusercontent.com/145541890/400605479-89c24be4-54d9-487e-bf3e-d4947f496d52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3MjQ0NzcsIm5iZiI6MTczNjcyNDE3NywicGF0aCI6Ii8xNDU1NDE4OTAvNDAwNjA1NDc5LTg5YzI0YmU0LTU0ZDktNDg3ZS1iZjNlLWQ0OTQ3ZjQ5NmQ1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExMlQyMzIyNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDNmM2U1NDgwNTVkZjM4ZmVmMWU0ZGRlZjJhN2I0MWYyODhhNzIzNDFkNjIxNzkwNGJiOWU4MmI2NTA1ZmNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mMiY4A30gCso7JB9KtIx4fNAQS9J5XzTn6ajtcV9GrU">

解决了 可以打印了 现在用sheets extend也没问题了 
居然还有跟进回复 谢谢大佬
