### ISSUE TITLE
Bad export row after list.

### ISSUE THREAD

**Issue by AP2020C** [l1xnan/obsidian-better-export-pdf#347]
```
My text
1. Lorem ipsum 
2. dolor sit amet,
3. consectetur adipiscing elit, sed
   Second line of point 3
A line after (and out of) the list

New paragraph
```
"A line after (and out of) the list" was exported as part of item 3, rather than separately, despite the fact that it was without tabulation. Obsidian shows attached but without indentation.

**Comment by arieltutu** [comment]
See If this will give you a hand. [Tab indents disappear in readermode](https://forum.obsidian.md/t/tab-indents-disappear-in-readermode/70765)

**Comment by AP2020C** [comment]
The behavior in Obsidian I think is correct. What I think needs to be corrected is the export in pdf: I would like it to appear indented as in Obsidian

**Comment by l1xnan** [comment]
@AP2020C 
![image](https://github.com/user-attachments/assets/27de5ad6-d531-4213-8400-ebba7191f62d)
OR
![image](https://github.com/user-attachments/assets/8014c01b-7cb0-4e02-bccb-fbf954f5ce18)

**Comment by arieltutu** [comment]
> The behavior in Obsidian I think is correct. What I think needs to be corrected is the export in pdf: I would like it to appear indented as in Obsidian

Yeah, but if you check your paragraph in read mode, you'll find the indentation line(without list syntax) being merged with the previous line. This is the thing I have encountered like yours.

**Comment by l1xnan** [comment]
@arieltutu Yes, the export's appearance is based on how it looks in read mode preview. In Markdown format, blank lines are needed to divide blocks. The preview mode is in line with the specification and expectation.

**Comment by AP2020C** [comment]
You are right, in reader mode the line is (uncomfortably) moved in line with the others. I think it's an Obsidian bug at this point.
It would make sense for the two views to be similar
