### ISSUE TITLE
Document name in header should be a choice

### ISSUE THREAD

**Issue by Calum-Quinn** [l1xnan/obsidian-better-export-pdf#352]
At the moment when you export, the file name is always shown in small text in the center of the header space.

This has nothing to do with the option to `Include file name as title` which works fine to add a large title at the top.

It would be nice to have the option of not adding the file name at all anywhere.

Thanks!

![image](https://github.com/user-attachments/assets/adb363a8-9e5a-45d2-a23f-bb541378df30)
![image](https://github.com/user-attachments/assets/02d2e152-c7a1-4940-977c-5614f44a1fe8)

**Comment by D-Gaspa** [comment]
I am pretty sure that happens when you have the display header option selected. You can either disable it in the plugin options or change what it should display. The header template is the following as default:

```html
<div style="width: 100vw;font-size:10px;text-align:center;"><span class="title"></span></div>
```

That is why you see the title centered at the header space.
