### ISSUE TITLE
Need to print in landscape instead of portrait

### ISSUE THREAD

**Issue by JESii** [l1xnan/obsidian-better-export-pdf#355]
Some of my documents are wide images that I need to send to others.

How do I print them in landscape; portrait makes them too "squished"

Thanks much!

**Comment by l1xnan** [comment]
Turn on the `Landscape` switch.
![image](https://github.com/user-attachments/assets/6a9b3a39-fde6-4e69-b2b5-0e3485b81a1c)

**Comment by JESii** [comment]
Terrific; thanks much..
