### ISSUE TITLE
macOS环境下无法自定义页边距

### ISSUE THREAD

**Issue by entps** [l1xnan/obsidian-better-export-pdf#36]
macOS环境下无法自定义页边距，，设置自定义页边距后单击导出PDF无任何响应。

**Comment by l1xnan** [comment]
具体设置的什么值呢? macOS 没有设备，我没有测过，页边距单位是默认英寸，大多数设置小数就好了(1cm≈0.4 inches)。在 Windows上设置成 `10`/`20` 之类的出现过无响应的情况，使用的是 [`<webview>.printToPDF`](https://www.electronjs.org/zh/docs/latest/api/webview-tag#webviewprinttopdfoptions) API，可能有什么限制，但是我没有找到相关资料，下个版本我把单位改成跟友好的毫米

**Comment by zhaoscsc** [comment]
无法设置边距。macOS和Windows都不行。换了不同的笔记文件也不行。

**Comment by l1xnan** [comment]
整个插件机制进行了重构，同时增加了导出预览功能，可以尝试新版本是否还有此问题
