### ISSUE TITLE
Can't print Chinese (zh-TW)

### ISSUE THREAD

**Issue by Andley** [l1xnan/obsidian-better-export-pdf#365]
Thansk for the great plug-in, but since Version 1.10.0 it can not print Chinese (zh-TW) ...

**Comment by l1xnan** [comment]
It shouldn't be like this. Open the console and check if there are any error messages.

**Comment by Andley** [comment]
no error message in the console ...
<img width="559" alt="console" src="https://github.com/user-attachments/assets/898bffec-2115-44f6-b65f-44de3943eebb" />

here is a compariosn of the MD and PDF snapshot:
<img width="1024" alt="obsidian" src="https://github.com/user-attachments/assets/78dcad7e-3e58-46fd-bbcb-d78f1d1636af" />

**Comment by l1xnan** [comment]
Then it should not be a problem with the plugin. Generally, this kind of issue is related to the operating system and the Electron version used by Obsidian. You can try reinstalling Obsidian.

**Comment by Andley** [comment]
Many thanks !! It works now😀

**Comment by Andley** [comment]
many thanks !!

after reinstalling, it works now.
