### ISSUE TITLE
大文档导出时间超长,10分钟了没有结果。

### ISSUE THREAD

**Issue by Kiss-World** [l1xnan/obsidian-better-export-pdf#41]
https://sspai.com/post/84373 

利用简悦 下载的 这篇文章的 md 版本。然后使用ob导出。

**Comment by l1xnan** [comment]
实际测试了一下，很快导出了，`ctrl+shift+i` 打开控制台看一下有没有什么报错

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/8a7af0c2-c4a2-4155-8038-7514ff19b01e)
