### ISSUE TITLE
感谢，解决了我的问题，可否把插件加入obsidian的商店里面？这样便于新建仓库的时候搜索

### ISSUE THREAD

**Issue by cr941131** [l1xnan/obsidian-better-export-pdf#51]
感谢，解决了我的问题，可否考虑把插件加入obsidian的商店里面？这样便于新建仓库的时候搜索

**Comment by l1xnan** [comment]
往插件仓库提交过PR，但是好久都没有被合入🤷‍♂️

**Comment by l1xnan** [comment]
这个插件最近已经上架到 obsidian 的商店，可以直接下载使用，感谢您的关注和支持
