### ISSUE TITLE
Callout icons not exported

### ISSUE THREAD

**Issue by piotrnajda3000** [l1xnan/obsidian-better-export-pdf#52]
Hey, thank you for a plugin that works in generating a TOC! 

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/58721991/1b360c2f-d08f-44ca-b248-a21210379822)

**Comment by l1xnan** [comment]
@piotrnajda3000 Fixed in the latest version(1.2.0), and added some new features.
