### ISSUE TITLE
导出pdf的中文全变成乱码

### ISSUE THREAD

**Issue by djy1121** [l1xnan/obsidian-better-export-pdf#53]
如题
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/37651113/7bb3075c-c6cf-453a-8a75-03b9f4cee05a)

**Comment by l1xnan** [comment]
有测试样例么？这么久还没有遇到过这种情况

**Comment by shroro** [comment]
> 有测试样例么？这么久还没有遇到过这种情况
> Obsidian V1.5版本会出现这个问题（除了乱码，还有图片不显示），V1.4版本能正常使用该插件

**Comment by l1xnan** [comment]
1. 我现在使用的是最新的 1.5.3 版本，乱码问题没有出现，Windows用户可以打开如下路径
```
C:\Users\<username>\AppData\Local\Temp\Obdisian\exportsxxx
```
打开插件生成的临时 html 文件，看看是否有异常；看截图英文字符正常，中文字符乱码，怀疑是文件编码问题，还是需要提供下样例文件。

2. 图片不显示问题，已复现，下个版本修复

**Comment by l1xnan** [comment]
整个插件机制进行了重构，图片不显示问题已解决，同时增加了导出预览功能，可以尝试新版本是否还有此问题

**Comment by djy1121** [comment]
更新1.3.2版本后，导出pdf的中文已正常显示。
