### ISSUE TITLE
Bug: 导出的渲染问题

### ISSUE THREAD

**Issue by YIRU69** [l1xnan/obsidian-better-export-pdf#58]
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/48148292/67f257d9-9538-48a0-93b6-3f1dab963307)

当我使用插件进行到处的时候，出现了字体不一的问题，如图，图片使用的是行内图片，麻烦作者可以检查一下

另外一个建议是：希望能保存下次导出的设置，便于导出

**Comment by l1xnan** [comment]
关于保存和使用上一次导出设置功能已经添加了，字体不一的问题能提供个样例文件么?

**Comment by YIRU69** [comment]
[🔟GRE Math - 真题数二2011.md](https://github.com/l1xnan/obsidian-better-export-pdf/files/13769665/GRE.Math.-.2011.md)
上面的文件，你可以试试，问题是，我用了图片位置的css，可能跟这个用关

**Comment by YIRU69** [comment]
我重新在你的新版本的情况下，进行了测试，逐一排查发现，这个问题是 https://github.com/TfTHacker/obsidian42-strange-new-worlds 这个插件引起的，可能是某个css导致导出的问题

**Comment by YIRU69** [comment]
原因我大概也找到了，这个插件有一个引用的计数，会显示数字在右上角，由于图片是引用，所有会有一个引用计数，这样就可能破坏一些渲染吧
