### ISSUE TITLE
导出没有反应

### ISSUE THREAD

**Issue by yanshicheng** [l1xnan/obsidian-better-export-pdf#70]
大佬 点击导出选择目录后 没有反应也没有报错提示，大佬能优化下内置导出不

**Comment by l1xnan** [comment]
内置导出会直接打开PDF文件，没有给修改PDF的时机，也没有提供接口，目前没有好方法，只能抽空再逆向梳理下内置的导出流程

**Comment by l1xnan** [comment]
新版本逆向实现了官方的打印函数，速度和效果都比以前好很多，可以试用下，看是否满足你的需求

**Comment by yanshicheng** [comment]
<img width="951" alt="image" src="https://github.com/l1xnan/obsidian-better-export-pdf/assets/37960656/cc9c935a-ce29-4a96-8be7-dc2ab6297115">
打开空白 大佬

**Comment by l1xnan** [comment]
macOS 么? `ctrl+shift+i` 打开 Console 看有什么报错?

**Comment by yanshicheng** [comment]
<img width="588" alt="image" src="https://github.com/l1xnan/obsidian-better-export-pdf/assets/37960656/8805eeea-6cc2-4c87-9c68-4c3dac2272b6">
这个是报错

**Comment by l1xnan** [comment]
@yanshicheng 下载 1.2.1 版本试一下，新版本已经不需要 `previewMode` 模式了

**Comment by yanshicheng** [comment]
我用的还是内侧版本 1.5x 的

**Comment by l1xnan** [comment]
我说的是插件的 1.2.1 版本，不是 Obsidian 的版本

**Comment by yanshicheng** [comment]
好的 大佬

**Comment by yanshicheng** [comment]
<img width="629" alt="image" src="https://github.com/l1xnan/obsidian-better-export-pdf/assets/37960656/b1547b7e-58e0-4888-b9c5-def522bf03e3">
这个属性报错了

**Comment by l1xnan** [comment]
估计是挂到这一行了
```js
const view = plugin.app.workspace.getActiveViewOfType(MarkdownView) as MarkdownView;
... ...
await MarkdownRenderer.render(plugin.app, view.data, viewEl, file.path, comp);
```
`view` 获取为空，我看看能不能换个API，不知道 macOS 为啥会这样

**Comment by yanshicheng** [comment]
好的大佬 可以开一个 虚拟机 搞个 mac 系统测一下

**Comment by l1xnan** [comment]
能帮忙测一下，通过命令面板打开输入 `Better Export PDF` 打开导出窗口看看是否有报错么？

**Comment by yanshicheng** [comment]
这个可以大佬，目录格式有点小问题 
<img width="483" alt="image" src="https://github.com/l1xnan/obsidian-better-export-pdf/assets/37960656/c51d90da-fc69-4463-8812-75441a4cde8a">

**Comment by l1xnan** [comment]
文件名有个选项可以不加，你那个数字是大纲级别吧，补充大纲序号??

**Comment by yanshicheng** [comment]
/* 链接 links 文字字体和颜色 */
a {
  color: rgba(16, 14, 66, 0.8);
  font-family: Menlo;
}
/* 页面边距 */
/* .markdown-preview-view  {margin-top:20px;margin-left:25px;} */
/* Bold加黑的颜色和字体 */

.markdown-preview-section strong {color: #075378;font-family: Menlo;}
/* 标题颜色、字体、间距、版式 */
/* h6标题颜色字体；h2标题下方线条、上下方间距；h2标题颜色和阴影；h1标题上下方间距；h1标题版式对中。 */ 
.markdown-preview-view h6 { color: #ae1c1e;font-family:Menlo;}
.markdown-preview-view h4 { border-bottom: 6px solid rgb(215, 216, 217) ;
                            margin-top: 4em;margin-bottom: 2em;}
.markdown-preview-view h3 { border-bottom: 6px solid rgb(215, 216, 217) ;
                            margin-top: 4em;margin-bottom: 2em;}
.markdown-preview-view h2 {text-shadow: 3px 3px 3px #FF8800;}
.markdown-preview-view h1 { margin-top: 2px;margin-bottom: 1em;}
h1 {text-align:center;}
/* 引用文本块颜色、字体 */
blockquote p {color: #1d648a;font-family: 楷体;}

/* 
段落缩进
编辑模式下的段落缩进。对象包括段落，标题，但不包括引用、列表。
换行段落均会引起缩进。 */
/* .markdown-source-view.mod-cm6  {text-indent: 2em;} */
/* 引用块整体缩进 */
/* 段落缩进后，引用块整体缩进才能对齐，达到美观效果。 */
.cm-s-obsidian span.cm-formatting-quote {
  margin-left: 2em;
  padding-left: 0em;
}
/* 列表整体缩进 */
/* 段落缩进后，列表整体缩进才能对其和美观。代码也改变了列表标记的颜色。 */
.cm-s-obsidian .cm-formatting-list {
  color: #229999;
  margin-left: 2em;
  padding-left: 0em;
}
/* 标题字体大小 */
/* 设置编辑器中标题字体大小。大小为本人认为比较协调的数值，可自行调整。 */
body {
--h1-size: 1.9em;
--h2-size: 1.5em;
--h3-size: 1.35em;
--h4-size: 1.2em;
--h5-size: 1.1em;
--h6-size: 1em;
}
/* 标题颜色和字体 */
/* 设置编辑器中标题字体及颜色。 */
body {--h1-color: #d26870;--h2-color: #2c656a;--h3-color: #144f92;--h4-color: #25356d;
      --h5-color:   #1d5e14; --h6-color:  #1d5e14;}
body {--h1-font: 楷体; --h2-font: Menlo; --h3-font: 宋体; --h4-font: 楷体; 
      --h5-font: 宋体; --h6-font: Menlo; }
/* 标题版式对中 */
/* 标题1的版式对中 。 */
/* .HyperMD-header-1  {text-align:center;} */
/* 标题字体颜色和阴影 */
/* 标题2的字体颜色和阴影 。 */
.cm-header-2 { text-shadow: 1px 0px 1px #FF8800;}
/* 下划线文本的颜色 */
/* 编辑模式和预览模式下均有效。 */
u {color: #24315b;}
/* 链接 links 文字字体和颜色 */
.cm-s-obsidian span.cm-link, .cm-s-obsidian span.cm-hmd-internal-link {
  color:  rgba(16, 14, 66, 0.8) !important;
  font-family: Menlo;
}
[export.pdf](https://github.com/l1xnan/obsidian-better-export-pdf/files/13803861/export.pdf)

在在 .obsidian/snippets/style.css 内容如上，设置开启这个css ob 自带的导出 会有效果加持例如颜色等。但是您这个好像漏掉了一些样式，但是已经满足的需要了，希望大佬有时间可以优化下，带
[export222.pdf](https://github.com/l1xnan/obsidian-better-export-pdf/files/13803862/export222.pdf)
 222 是您插件导出的，不带的是ob默认的

**Comment by yanshicheng** [comment]
我看了后面的数字是第几页，这个可以去掉吗

**Comment by l1xnan** [comment]
页眉页脚可以 `Display header/footer` 配置关闭，或者在插件设置中自定义 `Footer Template`

**Comment by l1xnan** [comment]
样式我看主要是颜色有不一致问题，你那个样式是自定义的样式片段添加的，还是主题样式？

**Comment by yanshicheng** [comment]
<img width="890" alt="image" src="https://github.com/l1xnan/obsidian-better-export-pdf/assets/37960656/9998e26d-7c14-42b8-9208-a4905348e794">
<img width="853" alt="image" src="https://github.com/l1xnan/obsidian-better-export-pdf/assets/37960656/38b1a0e6-0206-4de0-88ff-276b75ed7fa3">
css 就是我上面提交的内容，其他的没有别的设置了，

**Comment by l1xnan** [comment]
OK, 我在测一下样式片段问题，刚发布了 1.2.2 版本，盲猜改了点代码，看看能不能解决 `data` 为空问题，也麻烦帮忙测一下

**Comment by yanshicheng** [comment]
好的大佬

**Comment by yanshicheng** [comment]
牛 可以了大佬。
文件名 和 页面序号去不掉。Footer Template 清空 Display header/footer 等选项都测试了也不生效
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/37960656/3c6b33e4-aac8-4b21-b413-d53212932d68)

**Comment by l1xnan** [comment]
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/7cdbe7b8-5d3f-4623-8cfd-bb08adc85808)

**Comment by yanshicheng** [comment]
add filename title 测试了 不行还是会添加文件名

**Comment by l1xnan** [comment]
Console 有啥报错么？我这边测试OK
[Video1.webm](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/d134ab9d-1aed-4958-b525-9e5380e4c962)

https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/d134ab9d-1aed-4958-b525-9e5380e4c962

**Comment by yanshicheng** [comment]
问题了大佬 我是在后台设置的，导出这里没设置

**Comment by l1xnan** [comment]
`modal` 设置会覆盖后台设置, 然后还会记住上一次设置, 只有 modal 没有设置, 才会用后台的值, 我应该删除一个设置入口, 这样不容易让人迷惑

**Comment by l1xnan** [comment]
另外主题颜色问题已修复, 逆向官方实现,还是漏了点东西, 见 1.2.3 版本

**Comment by yanshicheng** [comment]
v5 我去测试下

**Comment by yanshicheng** [comment]
<img width="593" alt="image" src="https://github.com/l1xnan/obsidian-better-export-pdf/assets/37960656/b8ae5b7a-f720-4929-be12-2d4f1412bc74">
我这测试还是没有颜色

**Comment by l1xnan** [comment]
我这边用的 Minimal 主题, 样式丢失是因为少复制了 `body.class` 属性, 打开调试模式, 点击 `Debug`, 看看你那边有没有问题
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/64781dcb-c16b-43e2-8c8c-8eed14b89db4)

**Comment by yanshicheng** [comment]
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/37960656/6b0ffca1-8e3a-423f-97a6-98a949b4b2fa)
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/37960656/3a840732-270b-4785-b0e7-6ba8a76dde67)
是的没有您说的

**Comment by l1xnan** [comment]
那估计是通过 `insertCSS` 向预览组件 `webview` 注入样式, 和正常的样式渲染有差异, 我再调试下😂

**Comment by l1xnan** [comment]
@yanshicheng 发布了一个新版本(1.3.2)，看主题颜色问题是否修复了

**Comment by yanshicheng** [comment]
解决了，👍 牛逼大佬
