### ISSUE TITLE
MacOS升级后预览失败，，导出只有一页，且只有标题

### ISSUE THREAD

**Issue by entps** [l1xnan/obsidian-better-export-pdf#73]
MacOS升级后预览失败，，导出只有一页，且只有标题

**Comment by l1xnan** [comment]
macOS没有测过，不知道是不是有啥差异，今天逆向参考官方的导出函数，又实现了一个版本，用 1.2.0 版本再试下😂

**Comment by entps** [comment]
TKS



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年12月31日 14:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [l1xnan/obsidian-better-export-pdf] MacOS升级后预览失败，，导出只有一页，且只有标题 (Issue #73) |

macOS没有测过，不知道是不是有啥差异，今天逆向参考官方的导出函数，又实现了一个版本，用 1.2.0 版本再试下😂
