### ISSUE TITLE
macOS 文件中的 SVG 图片导不出来

### ISSUE THREAD

**Issue by entps** [l1xnan/obsidian-better-export-pdf#75]
测试过，，，Obsidian 标准的 PDF 导出是可以导出 SVG的，，，better export pdf 导不出来，其他方面暂未发现问题

**Comment by l1xnan** [comment]
导出预览是否能正常显示 SVG 图片？

在 Windows 上插件最新 1.2.4 版本测试 OK
https://en.wikipedia.org/wiki/SVG#/media/File:SVG_Logo.svg

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/14e3302b-137c-4062-a68c-55834af91c51)


![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/15c6d3a6-be63-40bd-be0c-0046888268af)

**Comment by entps** [comment]
OK了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月03日 21:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [l1xnan/obsidian-better-export-pdf] macOS 文件中的 SVG 图片导不出来 (Issue #75) |

导出预览是否能正常显示 SVG 图片？

在 Windows 上插件最新 1.2.4 版本测试 OK
https://en.wikipedia.org/wiki/SVG#/media/File:SVG_Logo.svg

image.png (view on web)

image.png (view on web)
