### ISSUE TITLE
macOS 又发现新问题，，，表格跨页分页逻辑有些Bug

### ISSUE THREAD

**Issue by entps** [l1xnan/obsidian-better-export-pdf#76]
<img width="1506" alt="iShot_2024-01-04_09 21 25" src="https://github.com/l1xnan/obsidian-better-export-pdf/assets/125341841/38fdac5d-33d1-426c-afc2-fd3f68988c27">
<img width="1075" alt="iShot_2024-01-04_09 21 06" src="https://github.com/l1xnan/obsidian-better-export-pdf/assets/125341841/987bbc40-a088-4194-9274-cba87fafe386">

**Comment by l1xnan** [comment]
发个样例文本看看

**Comment by entps** [comment]
吴建忠
13928500723
***@***.***
佛山市恩特普斯管理咨询有限公司 资深实施顾问


在 2024年1月4日 ***@***.***> 写道：


发个样例文本看看

**Comment by entps** [comment]
不好意思，刚才发错了，，现在这个才是正确的






在 2024年1月4日 ***@***.***> 写道：


发个样例文本看看

**Comment by entps** [comment]
不好意思，刚才发错了，，现在这个才是正确的


只有在特定的上面边距时才可以导出正确的PDF，，，例如这个文档，上下边距使用 10 时，，导出是没问题的，，，上下边距使用 15 时，导出就会出问题，，，逻辑上应该将前一面没有完全显示的行放置在下一页，，，这样才是正确的






在 2024年1月4日 ***@***.***> 写道：


发个样例文本看看

**Comment by l1xnan** [comment]
估计要通过电脑回复上传样例我才能看到，通过邮件回复看不到

**Comment by entps** [comment]
[20240103190357805.md](https://github.com/l1xnan/obsidian-better-export-pdf/files/13827517/20240103190357805.md)

**Comment by l1xnan** [comment]
我找了个大表格在 Windows 上复现这个问题(默认边距和自定义边距都存在这个问题)，但是官方的导出也同样复现了这个问题。导出PDF功能底层都是调用的 Chrome 的网页转PDF接口，这应该是底层的缺陷，目前插件对这种情况无能为力。

不过应该可以通过自定义打印相关的 css 调整优化大表格导出问题，这个需要花时间研究下相关的 CSS 规范，短时间没有很好的规避方案。

**Comment by l1xnan** [comment]
@entps 针对你这个表格问题，通过在`外观>CSS代码片段`添加如下样式片段可以解决：

```css
@media print {
  table {
    page-break-inside: auto;
  }
  tr {
    page-break-inside: avoid;
    page-break-after: auto;
  }
}
```
我会在下一个版本把它添加到插件的默认样式中，它应该能解决大多数问题
