### ISSUE TITLE
1.1.0 版本还可以正常导出的文档，在往高版本就不行了

### ISSUE THREAD

**Issue by plutoghost** [l1xnan/obsidian-better-export-pdf#77]
文档是用dataview生产的，内嵌图片也比较多

**Comment by l1xnan** [comment]
1.1.0 之后版本插件改了机制，对 dataview 支持是有问题，还在想办法修复，感谢反馈

**Comment by l1xnan** [comment]
我这边复现发现 dom 渲染 ready, dataview 并没有渲染完成，针对这种情况添加了 2s 的延迟，新版本已发布，看是否能解决你的问题

**Comment by plutoghost** [comment]
> 我这边复现发现 dom 渲染 ready, dataview 并没有渲染完成，针对这种情况添加了 2s 的延迟，新版本已发布，看是否能解决你的问题

可以了，谢谢
