### ISSUE TITLE
导出后，会执行一下  Ctrl + - ，使得界面变小一点

### ISSUE THREAD

**Issue by Kiss-World** [l1xnan/obsidian-better-export-pdf#78]
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/44720566/a57726e4-52fe-4e56-b8d6-9388015c1a52)

**Comment by l1xnan** [comment]
你用的是哪个版本？缩放预览界面的时候，老版本用的是 webview 自带的缩放API，但是这个接口有个问题会缩放同源的主界面，后面改成用 css 的 transform 属性缩放应该解决了这个问题。

**Comment by Kiss-World** [comment]
@l1xnan 使用的是最新的版本，我有使用rss接收你的更新信息，所以换了最新的，客户端是1.5.3 windows11 。

现在这个使用起来已经好非常多了。提个小建议 顶部信息和页码建议分成两个开关

**Comment by l1xnan** [comment]
我这边插件 1.2.6 版本确实没有复现你说的问题。
页眉/页脚启用对应在底层接口上是一个配置 `displayHeaderFooter`, 只能同时开启或者关闭:
```
<webview>.printToPDF({
  displayHeaderFooter: boolean,
  headerTemplate: string,
  footerTemplate: string,
})
```
目前如果不想显示页眉，可以把 `Header Template` 改成空值。不过倒是可以让 `displayHeaderFooter` 始终为 `true`, 然后通过 `headerTemplate`/`footerTemplate` 是否赋空来实现分开控制的效果，下个版本看看效果

**Comment by l1xnan** [comment]
@Kiss-World 缩放确实发现了一个问题，猜测你这边是不是在主设置中改了默认的缩放设置，我这边在修复同源缩放问题的时候少删除了一行代码，估计就是造成 issue 中问题的原因：
https://github.com/l1xnan/obsidian-better-export-pdf/commit/5430124407b018ece3a6e35714a040bd728545d9

**Comment by l1xnan** [comment]
页眉页脚以及分开设置，见 1.3.0 版本
