### ISSUE TITLE
bug: 新版本无法导出以及嵌入效果不佳

### ISSUE THREAD

**Issue by YIRU69** [l1xnan/obsidian-better-export-pdf#84]
你好作者！

使用1.3版本，无法导出 如图
```
Error: Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error: Failed to generate PDF: Printing failed
    at t.ipcRendererInternal.invoke (node:electron/js2c/renderer_init:2:11899)
    at async exportToPDF (plugin:better-export-pdf:20090:16)
    at async handleExport (plugin:better-export-pdf:20338:11)
```

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/48148292/4db87fc2-8b5e-4dae-b50a-3b5114a07295)

我对比了使用导出片段用ob原生的pdf导出嵌入效果，我使用插件进行导出进行了对比
使用插件导出的嵌入效果并不好，上下空隙太大了，如图

- 原生pdf导出
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/48148292/a5b62a68-cc76-4e24-8076-7ab991ad3278)

- 插件pdf导出，中间的空隙很大
由于用新版本无法导出，我是在1.2.6版本导出的，文件覆盖了，作者可以复现一下

我用的导出片段

```css
/* 嵌入效果的打印 */
@media print {

  .markdown-preview-view .markdown-embed { border:none; padding:0; margin:0; }
  .markdown-preview-view .markdown-embed-content { 
  max-height: unset;
  background-color: transparent; /*define different bg color*/
}
.markdown-preview-view div.markdown-embed {
    border-top: 0px !important;
    border-bottom: 0px !important;
}
}
```

**Comment by l1xnan** [comment]
1. 导出报错是底层 electron 报的错，不是插件报的错，重启下 Obsidian 试试
2. 你说的嵌入指的是什么?

**Comment by YIRU69** [comment]
> 2. 你说的嵌入指的是什么?

嵌入是指 ![[xxx.md^#片段]]

**Comment by l1xnan** [comment]
大致找到原因了，插件渲染少了一层 `.markdown-embed` 嵌套，造成 css 没有生效

**Comment by l1xnan** [comment]
已修复，见 `1.3.1` 版本
