### ISSUE TITLE
导出失败

### ISSUE THREAD

**Issue by Sleepleeps** [l1xnan/obsidian-better-export-pdf#93]
安装好插件后，导出的pdf是一页奇怪的东西
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/37953116/82a5168a-e26e-4f4e-973c-197b83eb214e)
这个网站我逛过，也做了个html玩，我猜可能是缓存？但是无论我用obsidian里什么文档导出都是这个界面，感觉很奇怪。
大佬可以告诉我为什么吗

**Comment by l1xnan** [comment]
1. 官方导出是否有这个问题？
2. 有复现样例文本么？
3. 导出预览是否会看到这个内容?

**Comment by Sleepleeps** [comment]
1. 官方导出是正常的
2. 复现样例文本是什么意思呀？
3.导出预览是正常的，可以正常预览文本的打印状况，但是导出就变了。好怪

**Comment by l1xnan** [comment]
页眉页脚有没有自己做啥定义？换个valt会不会复现？
