### ISSUE TITLE
怎样修改页眉和正文的间距？

### ISSUE THREAD

**Issue by Ltjwork** [l1xnan/obsidian-better-export-pdf#94]
如题

**Comment by l1xnan** [comment]
通过自定义页边距和修改页眉页脚模板可以修改，类似这样的：
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/33dbe33f-eb44-462b-a25d-75b1c96e3a36)

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/160c5200-c062-4e45-9ffc-72152ad6cb8d)

```diff
-<div style="width: 100vw;font-size:10px;text-align:center;"><span class="title"></span></div>
+<div style="width: 100vw;font-size:10px;text-align:center;margin-top:30px;"><span class="title"></span></div>
```
