### ISSUE TITLE
Failed to load plugin better-export-pdf

### ISSUE THREAD

**Issue by lululu-lp** [l1xnan/obsidian-better-export-pdf#95]
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/114970563/304f9c44-cca0-4eff-8023-d5b7d1ce4aba)
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/114970563/cf6caa5a-fb1b-478e-b3bb-852886ff4de5)
obsidian 1.5.3

**Comment by l1xnan** [comment]
Which one does the installation package download?

![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/faf7caf4-6988-457c-bf75-a045528fb3fc)

**Comment by lululu-lp** [comment]
Appreciation! I reinstalled the plugin and this time it worked!
